"""All user-facing strings, Persian (fa) + English (en). add(key, fa, en)."""
T = {"fa": {}, "en": {}}

def add(key, fa, en):
    T["fa"][key] = fa
    T["en"][key] = en

# ---------- language / welcome / help ----------
add("pick_lang", "🌐 زبان را انتخاب کن / Choose your language:", "🌐 زبان را انتخاب کن / Choose your language:")
add("lang_set", "✅ زبان روی فارسی تنظیم شد 💖", "✅ Language set to English 💖")
add('welcome', '📥 <b>به SaveIt خوش اومدی!</b> 💖\n\nفقط یه لینک برام بفرست، فایلش رو برات می\u200cگیرم ✨\n▶️ یوتیوب (شورت و ویدیوی بلند)\n📸 اینستاگرام (پست، ریلز، استوری، هایلایت، عکس پروفایل)\n🎵 تیک\u200cتاک (بدون واترمارک تا جای ممکن)\n📌 پینترست (عکس و ویدیو)\n💼 لینکدین (پست‌های عمومی: ویدیو و عکس)\n🧵 تردز (ویدیو، عکس و چندرسانه‌ای)\n🐦 توییتر / ایکس (ویدیو، گیف، عکس)\n☁️ ساندکلود (آهنگ و پلی\u200cلیست)\n🎧 اسپاتیفای (آهنگ، آلبوم، پلی\u200cلیست — از یوتیوب پیدا می\u200cشه)\n🎶 شناسایی آهنگ: ویس، فایل صوتی یا کلیپ بفرست!\n\n🎬 ویدیو، 🎵 فقط صدا، 🖼 عکس — هرچی بخوای!\n👇 یه لینک بفرست یا از منو انتخاب کن', "📥 <b>Welcome to SaveIt!</b> 💖\n\nJust send me a link and I'll fetch the file for you ✨\n▶️ YouTube (Shorts & long videos)\n📸 Instagram (posts, reels, stories, highlights, profile pictures)\n🎵 TikTok (no watermark when possible)\n📌 Pinterest (images & videos)\n💼 LinkedIn (public posts: video & images)\n🧵 Threads (video, photos, carousels)\n🐦 Twitter / X (video, GIF, photos)\n☁️ SoundCloud (tracks & sets)\n🎧 Spotify (tracks, albums, playlists — matched from YouTube)\n🎶 Song recognition: send a voice message, audio file or clip!\n\n🎬 Video, 🎵 audio only, 🖼 photos — whatever you like!\n👇 Send a link or pick from the menu")
add("help",
    "ℹ️ <b>راهنمای SaveIt</b>\n\n"
    "1️⃣ لینک (یا چند لینک) رو بفرست\n"
    "2️⃣ کیفیت یا نوع فایل رو با دکمه‌ها انتخاب کن\n"
    "3️⃣ فایل رو تحویل بگیر 🎁\n\n"
    "📸 برای عکس پروفایل اینستاگرام، یوزرنیم (مثل <code>@username</code>) یا لینک پروفایل رو بفرست.\n"
    "📖 استوری و هایلایت اینستاگرام: لینکش یا یوزرنیم رو بفرست (نیاز به فعال‌سازی توسط ادمین دارد).\n"
    "📦 محدودیت تلگرام برای ربات‌ها ۵۰ مگابایت است؛ اگر فایل بزرگ‌تر بود، خودم کیفیت پایین‌تر انتخاب می‌کنم یا فقط صدا پیشنهاد می‌دم.\n\n"
    "💼 لینکدین: لینک پست عمومی (ویدیو یا عکس)؛ پست خصوصی یا نیازمند ورود قابل دانلود نیست. 🧵 تردز (threads.net / threads.com) و 🐦 توییتر/ایکس (twitter.com / x.com / t.co): لینک پست عمومی با ویدیو، گیف یا عکس (چندتایی هم می‌شه)؛ پست فقط‌متنی یا خصوصی/حذف‌شده رسانه‌ای نداره. ☁️ ساندکلود: لینک آهنگ یا پلی‌لیست (set). 🎧 اسپاتیفای: لینک آهنگ، آلبوم یا پلی‌لیست — اسپاتیفای فایل صوتی نمی‌دهد، پس آهنگ رو با اطلاعاتش از منابع موسیقی (رادیو جوان، ساندکلود، آدیوس، بندکمپ؛ آخرین راه: یوتیوب موزیک) پیدا می‌کنم و منبعش رو بهت می‌گم (ممکنه گاهی نسخه‌ی دقیق نباشه).\n"
    "🎶 <b>شناسایی آهنگ:</b> یه ویس، فایل صوتی یا ویدیو (تا ۲۰ مگابایت) بفرست؛ آهنگ رو پیدا می‌کنم و با دکمه می‌تونی دانلودش کنی. بهترین نتیجه: ۱۰ تا ۲۰ ثانیه موزیک واضح، بدون نویز. زمزمه کردن پشتیبانی نمی‌شه. 🔎 اسم آهنگ یا خواننده (فارسی یا انگلیسی) رو بنویس یا /music بزن تا جستجو کنم.\n"
    "🎼 از آلبوم/پلی‌لیست حداکثر {max_tracks} آهنگ اول گرفته می‌شود.\n\n"
    "🆓 سهمیه‌ی رایگان روزانه برای هر پلتفرم جداست؛ /me رو ببین.\n"
    "دستورها: /start · /help · /about · /lang · /plans · /me · /invite · /music · /theme\n\n"
    "⚖️ <b>تذکر:</b> مسئولیت رعایت حقوق صاحبان محتوا با خود شماست. فقط محتوایی را دانلود کن که اجازه‌ی دانلودش را داری.",
    "ℹ️ <b>SaveIt help</b>\n\n"
    "1️⃣ Send a link (or several)\n"
    "2️⃣ Pick the quality / file type with the buttons\n"
    "3️⃣ Get your file 🎁\n\n"
    "📸 For an Instagram profile picture, send a username (like <code>@username</code>) or a profile link.\n"
    "📖 Instagram stories & highlights: send the link or a username (the admin must enable this).\n"
    "📦 Telegram limits bots to 50 MB; for bigger files I pick a lower quality automatically or offer audio only.\n\n"
    "💼 LinkedIn: public post links (video or images); private / login-only posts can't be downloaded. 🧵 Threads (threads.net / threads.com) and 🐦 Twitter/X (twitter.com / x.com / t.co): public post links with video, GIF or photos (several media are fine); text-only, private or deleted posts have no media to download. ☁️ SoundCloud: track or set links. 🎧 Spotify: track, album or playlist links — Spotify doesn't serve audio files, so I find the song from music sources (Radio Javan, SoundCloud, Audius, Bandcamp; YouTube Music as a last resort) and tell you which source it came from (it may occasionally not be the exact version).\n"
    "🎶 <b>Song recognition:</b> send a voice message, audio file or video (up to 20 MB); I'll identify the song and you can download it with a button. Best results: 10–20 seconds of clear music, little noise. Humming is not supported. 🔎 Type a song or artist name (Persian or English) or use /music to search.\n"
    "🎼 Albums/playlists: only the first {max_tracks} tracks are taken.\n\n"
    "🆓 The free daily quota is separate for each platform; see /me.\n"
    "Commands: /start · /help · /about · /lang · /plans · /me · /invite · /music · /theme\n\n"
    "⚖️ <b>Notice:</b> you are responsible for respecting content owners' rights. Only download content you're allowed to download.")
add("menu_title", "یکی از گزینه‌ها رو انتخاب کن 👇", "Pick an option 👇")
add("b_send", "🔗 چطور لینک بفرستم؟", "🔗 How to send a link")
add("b_plans", "💎 پلن‌ها", "💎 Plans"); add("b_me", "👤 حساب من", "👤 My account")
add("b_invite", "🎁 دعوت دوستان", "🎁 Invite friends"); add("b_lang", "🌐 زبان", "🌐 Language")
add("b_help", "ℹ️ راهنما", "ℹ️ Help"); add("b_admin", "🛠 پنل ادمین", "🛠 Admin panel")
add("b_menu", "🏠 منو", "🏠 Menu"); add("b_share", "📤 اشتراک‌گذاری", "📤 Share")
add("b_contact", "💬 پیام به ادمین", "💬 Contact admin")
add("b_support1", "💬 پشتیبان ۱", "💬 Support 1"); add("b_support2", "💬 پشتیبان ۲", "💬 Support 2")
add('how_send', '🔗 لینک یوتیوب، اینستاگرام، تیک\u200cتاک، پینترست، لینکدین، تردز، توییتر/ایکس، ساندکلود یا اسپاتیفای رو اینجا بفرست (یا پیست کن)؛ چند لینک هم اجازه داری! 😉\n📸 یا یه یوزرنیم اینستاگرام مثل <code>@username</code> برای عکس پروفایل.\n🎶 یا یه ویس/آهنگ/کلیپ برای شناسایی آهنگ.', '🔗 Just send (paste) a YouTube, Instagram, TikTok, Pinterest, LinkedIn, Threads, Twitter/X, SoundCloud or Spotify link here — several links are fine too! 😉\n📸 Or an Instagram username like <code>@username</code> for the profile picture.\n🎶 Or a voice/audio/clip to recognize a song.')
add("yes", "✅ بله", "✅ Yes"); add("no", "❌ خیر", "❌ No")
add("on", "روشن ✅", "On ✅"); add("off", "خاموش ⛔", "Off ⛔")
add("cancelled", "لغو شد 👌", "Cancelled 👌")
add("unexpected", "❌ خطای غیرمنتظره رخ داد. دوباره امتحان کن.", "❌ Unexpected error. Please try again.")
add("banned", "🚫 دسترسی تو به ربات مسدود شده است.", "🚫 Your access to this bot has been blocked.")
add("unknown_cmd", "دستور نامعتبر است. /start را بزن 💖", "Unknown command. Send /start 💖")
add('no_link', '🤔 لینک معتبری پیدا نکردم. لینک یوتیوب، اینستاگرام، تیک\u200cتاک، پینترست، لینکدین، تردز، توییتر/ایکس، ساندکلود یا اسپاتیفای بفرست.', "🤔 I couldn't find a valid link. Send a YouTube, Instagram, TikTok, Pinterest, LinkedIn, Threads, Twitter/X, SoundCloud or Spotify link.")
add("expired", "⌛ این دکمه منقضی شده؛ لطفاً لینک را دوباره بفرست.", "⌛ This button has expired — please send the link again.")
add("not_yours", "این دکمه برای تو نیست 🙈", "That button isn't yours 🙈")

# ---------- account / plans / quota / referral ----------
add("me_head", "👤 <b>حساب تو</b>", "👤 <b>Your account</b>")
add("me_admin", "👑 نقش: ادمین (نامحدود)", "👑 Role: admin (unlimited)")
add("me_unl", "♾ دسترسی: نامحدود", "♾ Access: unlimited")
add("me_until", "📅 دسترسی نامحدود تا: {date}", "📅 Unlimited until: {date}")
add('me_free', '🆓 سهمیه\u200cی رایگان امروز: {n} از {total}', '🆓 Free downloads left today: {n} of {total}')
add("me_credits", "💎 اعتبار دانلود: {n}", "💎 Download credits: {n}")
add("me_made", "📥 دانلودهای انجام‌شده: {n}", "📥 Downloads so far: {n}")
add("me_ref", "🎁 دعوت‌شده‌ها: {n} نفر · پاداش گرفته: {b} دانلود", "🎁 Invited: {n} · bonus earned: {b} downloads")
add("me_id", "🆔 شناسه‌ی عددی تو: <code>{uid}</code>", "🆔 Your numeric ID: <code>{uid}</code>")
add("note_one", "\n💬 پیام به ادمین: @{p}", "\n💬 Contact the admin: @{p}")
add("note_two", "\n💬 پشتیبان‌ها: @{p} · @{b}", "\n💬 Support: @{p} · @{b}")
add('quota_out', '🌙 {head}\n\n{left}{price}برای ادامه می\u200cتونی فردا برگردی، دوستانت رو دعوت کنی 🎁 یا یه پلن بگیری 💎\n💌 برای فعال\u200cسازی، به ادمین پیام بده و این شناسه\u200cی عددی\u200cات رو بفرست:\n🆔 <code>{uid}</code>{note}', '🌙 {head}\n\n{left}{price}Come back tomorrow, invite friends 🎁 or get a plan 💎\n💌 To activate, message the admin and send them your numeric ID:\n🆔 <code>{uid}</code>{note}')
add("plans_title", "💎 <b>پلن‌های SaveIt</b>", "💎 <b>SaveIt plans</b>")
add('plans_free', '🆓 <b>رایگان</b> (سهمیه\u200cی روزانه برای هر کاربر)\n{lines}', '🆓 <b>Free</b> (daily quota for every user)\n{lines}')
add("plans_card", "✨ <b>{title}</b>\n🎟 {count} دانلود\n💵 {price}{dur}{feats}", "✨ <b>{title}</b>\n🎟 {count} downloads\n💵 {price}{dur}{feats}")
add("plans_none", "🌷 پلن‌های پولی به‌زودی اضافه می‌شوند. فعلاً از سهمیه‌ی رایگان و دعوت دوستان استفاده کن!",
    "🌷 Paid plans are coming soon. For now enjoy the free daily quota and invite friends!")
add("plans_footer", "💌 برای فعال‌سازی یک پلن به ادمین پیام بده و این شناسه‌ی عددی‌ات رو بفرست:\n🆔 <code>{uid}</code>{note}",
    "💌 To activate a plan, message the admin and send this numeric ID:\n🆔 <code>{uid}</code>{note}")
add("pp_popular", "⭐ محبوب‌ترین", "⭐ Popular")
add("pp_head_user", "💰 پلن‌ها:", "💰 Plans:")
add('pp_free_line', '🆓 رایگان روزانه: {lines}', '🆓 Free daily: {lines}')
add("pp_user_line", "{star}✨ {title} — {count} دانلود — {price}", "{star}✨ {title} — {count} downloads — {price}")
add("invite_text", "🎁 <b>دعوت دوستان</b>\n\nلینک اختصاصی تو:\n{link}\n\n💎 <b>به ازای هر دوستِ جدید که با این لینک وارد ربات بشه، {bonus} دانلود هدیه می‌گیری!</b>{invitee_line}\n{cap_line}\n\n👥 تا حالا {n} نفر دعوت کردی و {earned} دانلود هدیه گرفتی.\n\n🎟 کد تخفیف داری؟ با دکمه‌ی پایین واردش کن.",
    "🎁 <b>Invite friends</b>\n\nYour personal link:\n{link}\n\n💎 <b>For every new friend who joins with this link you get {bonus} free downloads!</b>{invitee_line}\n{cap_line}\n\n👥 So far you invited {n} and earned {earned} downloads.\n\n🎟 Have a discount code? Enter it with the button below.")

add("invite_off", "🎁 سیستم دعوت فعلاً غیرفعال است.", "🎁 The referral program is currently off.")
add("invite_share_text", "📥 با SaveIt هر ویدیو و عکسی رو از یوتیوب، اینستاگرام، تیک‌تاک، پینترست، لینکدین، تردز و توییتر بگیر! 💖", "📥 Download videos & photos from YouTube, Instagram, TikTok, Pinterest, LinkedIn, Threads and Twitter/X with SaveIt! 💖")
add("invite_forward_hint", "👇 این پیام آماده‌ی فورواده؛ برای دوستانت بفرست یا دکمه‌ی اشتراک‌گذاری رو بزن:", "👇 This message is ready to forward — send it to friends or tap Share:")
add("ref_joined_referrer", "🎉 یه دوست جدید با لینک تو اومد! {bonus} دانلود هدیه گرفتی 💎", "🎉 A new friend joined with your link! You got {bonus} free downloads 💎")
add("ref_joined_invitee", "🎁 چون با لینک دعوت اومدی، {bonus} دانلود هدیه گرفتی 💎", "🎁 You joined via an invite link, so you got {bonus} free downloads 💎")
add("u_granted", "🎁 ادمین دسترسی نامحدود به تو داد! هر چقدر دلت خواست دانلود کن 🥳", "🎁 The admin gave you unlimited access! Download as much as you like 🥳")
add("u_days", "🎁 ادمین {n} روز دسترسی نامحدود به تو داد (تا {date}) 🥳", "🎁 The admin gave you {n} days of unlimited access (until {date}) 🥳")
add("u_revoked", "ℹ️ دسترسی ویژه‌ی تو توسط ادمین لغو شد.", "ℹ️ Your special access was revoked by the admin.")
add("u_credits", "🎁 ادمین {n} دانلود اعتبار به تو اضافه کرد 💎", "🎁 The admin added {n} download credits to your account 💎")

# ---------- channels gate ----------
add("gate_text", "🌷 <b>یه قدم تا شروع!</b>\nبرای استفاده از ربات اول تو کانال(های) زیر عضو شو، بعد دکمه‌ی «عضو شدم» رو بزن 💖",
    "🌷 <b>One step to go!</b>\nPlease join the channel(s) below to use the bot, then tap “I joined” 💖")
add("b_joined", "✅ عضو شدم / I joined", "✅ I joined / عضو شدم")
add("gate_still", "🙈 هنوز عضو همه‌ی کانال‌ها نیستی؛ عضو شو و دوباره بزن.", "🙈 You haven't joined every channel yet — join and tap again.")
add("gate_ok", "🎉 عالی! حالا می‌تونی از ربات استفاده کنی.", "🎉 Great! You can use the bot now.")
add("ch_open", "📌 {title}", "📌 {title}")

# ---------- download flow ----------
add("analyzing", "🔎 در حال بررسی لینک…", "🔎 Checking the link…")
add("queued", "🕐 تو صف هستی… (درخواست‌های قبلی‌ات تموم بشه شروع می‌کنم)", "🕐 Queued… I'll start once your previous request finishes")
add("busy_limit", "✋ چند درخواست فعال داری؛ صبر کن تا تموم بشن و بعد ادامه بده.", "✋ You already have several active requests — wait for them to finish.")
add("downloading", "⏳ در حال دانلود… {pct}", "⏳ Downloading… {pct}")
add("uploading", "📤 در حال آپلود…", "📤 Uploading…")
add("processing", "⚙️ در حال پردازش…", "⚙️ Processing…")
add("done_caption", "✅ {title}\n🤖 @{bot}", "✅ {title}\n🤖 @{bot}")
add("cancel_b", "✖️ لغو", "✖️ Cancel")
add("opt_video_title", "🎬 <b>{title}</b>\n{meta}\n\nچی برات بگیرم؟ 👇", "🎬 <b>{title}</b>\n{meta}\n\nWhat should I grab? 👇")
add("opt_gallery_title", "🖼 <b>{title}</b>\nپیدا شد: {n} مورد\n\nچی برات بگیرم؟ 👇", "🖼 <b>{title}</b>\nFound: {n} item(s)\n\nWhat should I grab? 👇")
add("opt_profile_title", "📸 <b>@{user}</b>\nچی برات بگیرم؟ 👇", "📸 <b>@{user}</b>\nWhat should I grab? 👇")
add("b_best", "🎬 بهترین (≤{mb}MB) · {q}p", "🎬 Best (≤{mb}MB) · {q}p")
add("b_best_plain", "🎬 ویدیو", "🎬 Video")
add("b_q", "🎬 {q}p{size}", "🎬 {q}p{size}")
add("b_mp3", "🎵 صدا (MP3)", "🎵 Audio (MP3)"); add("b_m4a", "🎧 صدا (M4A)", "🎧 Audio (M4A)")
add("b_photos", "🖼 عکس‌ها ({n})", "🖼 Photos ({n})"); add("b_files", "📎 به‌صورت فایل (کیفیت اصلی)", "📎 As files (original quality)")
add("b_all", "📦 همه ({n})", "📦 All ({n})")
add("b_profile", "📸 عکس پروفایل", "📸 Profile picture"); add("b_stories", "📖 استوری‌ها", "📖 Stories")
add("b_pick", "{n}️⃣", "{n}️⃣")
add("meta_line", "⏱ {dur} · 👤 {who}", "⏱ {dur} · 👤 {who}")
add("warn_big", "\n⚠️ کیفیت‌های علامت‌دار از ۵۰ مگابایت بزرگ‌ترند؛ خودم خودکار کیفیت مناسب رو انتخاب می‌کنم.", "\n⚠️ Qualities marked ⚠️ exceed 50 MB; I'll automatically pick one that fits.")
add("fit_lower", "ℹ️ فایل از ۵۰ مگابایت بزرگ‌تر می‌شد؛ کیفیت {q}p رو فرستادم 💖", "ℹ️ The file would exceed 50 MB, so I sent {q}p instead 💖")
add("too_big", "📦 این ویدیو حتی در پایین‌ترین کیفیت از ۵۰ مگابایتِ تلگرام بزرگ‌تره 😢\nمی‌تونم فقط صداش رو بفرستم یا یه کیفیت پایین‌تر امتحان کنی 👇",
    "📦 This video is over Telegram's 50 MB limit even at the lowest quality 😢\nI can send just the audio, or you can try a lower quality 👇")
add("audio_too_big", "📦 حتی صدای این ویدیو هم برای حد ۵۰ مگابایتی تلگرام خیلی طولانیه 😢", "📦 Even the audio of this video is too long for Telegram's 50 MB limit 😢")
add("sent_n", "✅ {n} فایل ارسال شد 💖", "✅ {n} file(s) sent 💖")
add("fit_audio", "ℹ️ برای جا شدن در ۵۰ مگابایت، کیفیت صدا رو به {k}kbps کم کردم.", "ℹ️ To fit in 50 MB I lowered the audio bitrate to {k} kbps.")
add("no_stories", "🤷 الان استوری فعالی پیدا نشد.", "🤷 No active stories found right now.")
add("cookies_needed",
    "🔒 این نوع محتوا (استوری/هایلایت/محتوای خصوصی اینستاگرام) فعلاً فعال نیست؛ باید ادمین فعالش کنه. بعداً امتحان کن یا به ادمین پیام بده 💖",
    "🔒 This kind of content (Instagram stories / highlights / private content) isn't enabled yet — the admin has to switch it on. Try again later or message the admin 💖")
add("err_private", "🔒 این حساب/محتوا خصوصیه و نمی‌تونم بهش دسترسی داشته باشم.", "🔒 This account/content is private, so I can't access it.")
add("err_login", "🔑 برای دیدن این محتوا ورود (لاگین) لازمه و الان دسترسی ندارم؛ شاید خصوصیه یا پلتفرم سرور من رو محدود کرده. بعداً امتحان کن یا به ادمین خبر بده.", "🔑 This content needs a login and I don't have access right now — it may be private or the platform is limiting my server. Try later or tell the admin.")
add("err_age", "🔞 این ویدیو محدودیت سنی داره و بدون ورود قابل دانلود نیست.", "🔞 This video is age-restricted and can't be downloaded without a login.")
add("err_geo", "🌍 این محتوا در منطقه‌ی سرور من در دسترس نیست (محدودیت جغرافیایی).", "🌍 This content isn't available from my server's region (geo-blocked).")
add("err_rate", "⏳ سرویس مقصد الان تعداد درخواست‌ها رو محدود کرده؛ چند دقیقه بعد دوباره امتحان کن.", "⏳ The platform is rate-limiting requests right now — try again in a few minutes.")
add("err_unsupported", "🤔 این لینک پشتیبانی نمی‌شه. یوتیوب، اینستاگرام، تیک‌تاک، پینترست، لینکدین، تردز یا توییتر/ایکس بفرست.", "🤔 This link isn't supported. Send YouTube, Instagram, TikTok, Pinterest, LinkedIn, Threads or Twitter/X.")
add("err_notfound", "🔍 چیزی پیدا نشد؛ شاید حذف شده، خصوصی باشه یا لینک اشتباهه.", "🔍 Nothing found — it may have been removed, be private, or the link is wrong.")
add("err_ipblock", "🚧 این پلتفرم دسترسی سرور من رو برای این محتوا مسدود کرده. چند دقیقه بعد یا با لینک دیگه امتحان کن.", "🚧 The platform is blocking my server's IP for this content. Try again later or with another link.")
add("err_timeout", "⏱ زمان دانلود طول کشید و متوقف شد. دوباره امتحان کن یا کیفیت پایین‌تر بخواه.", "⏱ The download took too long and was stopped. Try again or pick a lower quality.")
add("err_toolong", "📏 این ویدیو خیلی طولانیه و از حد مجاز من بیشتره.", "📏 This video is too long for my limits.")
add("err_nomedia", "🫥 رسانه‌ای برای دانلود توی این لینک پیدا نشد (پست فقط‌متنی یا بدون ویدیو/عکسه).", "🫥 No downloadable media found at this link (a text-only post has no video or photo).")
add("err_unknown", "😵 نشد! مشکلی پیش اومد و دانلود انجام نشد. دوباره امتحان کن؛ اگر تکرار شد به ادمین بگو.", "😵 Oops! Something went wrong and the download failed. Try again; if it repeats, tell the admin.")
add("err_upload", "😵 آپلود فایل به تلگرام ناموفق بود: {d}", "😵 Uploading to Telegram failed: {d}")
add("ad_label", "📢 <i>تبلیغ</i>", "📢 <i>Sponsored</i>")
add("b_ad_open", "🔗 باز کردن", "🔗 Open")
add("ad_click_msg", "🔗 {url}", "🔗 {url}")

# ---------- admin: general ----------
add("a_title", "🛠 <b>پنل ادمین SaveIt</b> 💖", "🛠 <b>SaveIt admin panel</b> 💖")
add("a_denied", "🔐 این بخش فقط برای مالک ربات است.", "🔐 This section is for the bot owner only.")
add("a_bound", "👑 شناسه‌ی عددی تو ({uid}) به‌عنوان مالک ثبت شد. از این پس فقط با شناسه‌ی عددی احراز می‌شوی. /admin را بزن.",
    "👑 Your numeric ID ({uid}) was registered as the owner. From now on you're identified by ID only. Send /admin.")
add("a_back", "⬅️ بازگشت", "⬅️ Back")
add("a_b_stats", "📊 آمار", "📊 Stats"); add("a_b_users", "👥 کاربران", "👥 Users")
add("a_b_grant", "🎁 اعطای دسترسی", "🎁 Grant access"); add("a_b_revoke", "⛔ لغو دسترسی", "⛔ Revoke")
add("a_b_credits", "➕ افزودن اعتبار", "➕ Add credits"); add("a_b_settings", "⚙️ تنظیمات", "⚙️ Settings")
add("a_b_bc", "📣 پیام همگانی", "📣 Broadcast"); add("a_b_ref", "🎁 دعوت‌ها", "🎁 Referrals")
add("a_b_admins", "👮 ادمین‌ها", "👮 Admins"); add("a_b_support", "💬 پشتیبانی", "💬 Support contacts")
add("a_b_prices", "💰 قیمت‌ها", "💰 Prices"); add("a_b_ads", "📢 تبلیغات", "📢 Ads")
add("a_b_channels", "📌 کانال‌های اجباری", "📌 Required channels")
add("a_b_cookies", "🍪 کوکی‌ها", "🍪 Cookies"); add("a_b_update", "🔄 به‌روزرسانی موتور", "🔄 Update engine")
add("a_b_ban", "🚫 بن / آن‌بن", "🚫 Ban / Unban"); add("a_b_errors", "🐞 خطاهای اخیر", "🐞 Recent errors")
add("a_stats",
    "📊 <b>آمار</b>\n\n👥 کاربران: {users} (فعال ۷ روز اخیر: {active})\n📥 دانلود موفق: {made}\n🔗 لینک‌های دریافتی: {links}\n"
    "❌ خطاها: {errors}\n💎 کاربران ویژه: {premium}\n🚫 مسدود: {banned}\n🎁 دعوت‌ها: {refs}\n\n📈 <b>دانلود به تفکیک پلتفرم</b>\n{plat}",
    "📊 <b>Stats</b>\n\n👥 Users: {users} (active in 7 days: {active})\n📥 Successful downloads: {made}\n🔗 Links received: {links}\n"
    "❌ Errors: {errors}\n💎 Premium users: {premium}\n🚫 Banned: {banned}\n🎁 Referrals: {refs}\n\n📈 <b>Downloads by platform</b>\n{plat}")
add("a_users", "👥 کاربران (صفحه {page}/{pages}، کل {total}):", "👥 Users (page {page}/{pages}, total {total}):")
add('a_user', '👤 {who}\n📥 دانلود: {made}\n🆓 سهمیه\u200cی امروز (باقی\u200cمانده):\n{free}\n💎 اعتبار: {credits}\n{status}\n🚫 وضعیت: {ban}', '👤 {who}\n📥 Downloads: {made}\n🆓 Free today (left):\n{free}\n💎 Credits: {credits}\n{status}\n🚫 Status: {ban}')
add("a_status_admin", "👑 ادمین", "👑 Admin"); add("a_status_unl", "♾ نامحدود", "♾ Unlimited")
add("a_status_until", "📅 نامحدود تا {date}", "📅 Unlimited until {date}"); add("a_status_quota", "🆓 عادی", "🆓 Normal")
add("a_ban_yes", "مسدود 🚫", "banned 🚫"); add("a_ban_no", "آزاد ✅", "active ✅")
add("a_ask_target", "🆔 شناسه‌ی عددی یا @نام‌کاربری کاربر را بفرست (باید قبلاً با ربات کار کرده باشد):\n(/cancel برای انصراف)", "🆔 Send the user's numeric ID or @username (they must have used the bot before):\n(/cancel to abort)")
add("a_not_found", "❌ کاربر پیدا نشد. دوباره بفرست یا /cancel.", "❌ User not found. Send again or /cancel.")
add("a_grant_choice", "🎁 اعطا به {who}:", "🎁 Grant to {who}:")
add("a_g_unl", "♾ نامحدود دائمی", "♾ Unlimited forever"); add("a_g_days", "📅 نامحدود N روز", "📅 Unlimited N days"); add("a_g_credits", "💎 افزودن اعتبار", "💎 Add credits")
add("a_ask_num", "🔢 {what} را به صورت عدد بفرست:", "🔢 Send {what} as a number:")
add("a_what_days", "تعداد روز", "number of days"); add("a_what_credits", "تعداد دانلود", "number of downloads")
add("a_bad_num", "عدد نامعتبر است؛ دوباره بفرست یا /cancel.", "Invalid number; send again or /cancel.")
add("a_done_grant", "✅ دسترسی نامحدود برای {who} ثبت شد.", "✅ Unlimited access granted to {who}.")
add("a_done_days", "✅ {n} روز نامحدود برای {who} (تا {date}).", "✅ {n} unlimited days for {who} (until {date}).")
add("a_done_credits", "✅ {n} دانلود به {who} اضافه شد.", "✅ {n} downloads added to {who}.")
add("a_confirm_revoke", "دسترسی ویژه‌ی {who} لغو شود؟", "Revoke {who}'s special access?")
add("a_done_revoke", "✅ دسترسی {who} لغو شد.", "✅ Access revoked for {who}.")
add("a_done_ban", "🚫 {who} مسدود شد.", "🚫 {who} banned."); add("a_done_unban", "✅ {who} آزاد شد.", "✅ {who} unbanned.")
add("a_b_ban1", "🚫 بن کردن", "🚫 Ban"); add("a_b_unban1", "✅ آن‌بن", "✅ Unban")
add("a_errors", "🐞 <b>خطاهای اخیر</b>\n\n{lines}", "🐞 <b>Recent errors</b>\n\n{lines}")
add("a_errors_none", "✨ خطایی ثبت نشده.", "✨ No errors recorded.")
add('a_settings', '⚙️ <b>تنظیمات</b>\n\n🆓 سهمیه\u200cی پیش\u200cفرض روزانه (برای پلتفرم\u200cهای بدون تنظیم جدا): {quota} دانلود برای هر پلتفرم (ادمین نامحدود)\n📢 تبلیغات: {ads} — هر {every} دانلود\n🎼 حداکثر آهنگ از آلبوم/پلی\u200cلیست: {tracks}', '⚙️ <b>Settings</b>\n\n🆓 Default daily quota (for platforms without their own setting): {quota} downloads per platform (admins unlimited)\n📢 Ads: {ads} — every {every} downloads\n🎼 Max tracks per album/playlist: {tracks}')
add("a_s_quota", "🆓 سهمیه‌ی روزانه", "🆓 Daily quota")
add("a_s_ask_num", "مقدار جدید را به صورت عدد بفرست (۰ تا ۱۰۰۰۰۰):", "Send the new value as a number (0 to 100000):")
add("a_s_saved", "✅ ذخیره شد.", "✅ Saved.")
add("a_bc_ask", "📣 متن پیام همگانی را بفرست:\n(/cancel برای انصراف)", "📣 Send the broadcast text:\n(/cancel to abort)")
add("a_bc_confirm", "📣 این پیام برای {n} کاربر فرستاده می‌شود:\n\n{text}\n\nتأیید؟", "📣 This will be sent to {n} users:\n\n{text}\n\nConfirm?")
add("a_bc_sending", "⏳ در حال ارسال…", "⏳ Sending…"); add("a_bc_none", "پیامی در انتظار نیست.", "No pending broadcast.")
add("a_bc_cancel", "لغو شد.", "Cancelled."); add("a_bc_done", "✅ ارسال شد. موفق: {ok} · ناموفق: {fail}", "✅ Done. Delivered: {ok} · Failed: {fail}")
add("a_ref", "🎁 <b>دعوت‌ها</b>\n\nوضعیت: {s}\nکل دعوت‌ها: {total}\nپاداش دعوت‌کننده: {rb} دانلود\nپاداش دعوت‌شده: {ib} دانلود\n\n🏆 برترین‌ها:\n{top}",
    "🎁 <b>Referrals</b>\n\nStatus: {s}\nTotal invites: {total}\nInviter bonus: {rb} downloads\nInvitee bonus: {ib} downloads\n\n🏆 Top inviters:\n{top}")
add("a_ref_none", "— هنوز کسی نیست —", "— nobody yet —")
add("a_s_rb", "➕ پاداش دعوت‌کننده", "➕ Inviter bonus"); add("a_s_ib", "➕ پاداش دعوت‌شده", "➕ Invitee bonus")
add("a_s_reftoggle", "🎁 دعوت‌ها: {s}", "🎁 Referrals: {s}")
# admins / support
add("ad_menu", "👮 <b>مدیریت ادمین‌ها</b>\n\n👑 مالک: {owner}\n\n👮 ادمین‌های اضافه:\n{lines}\n\nادمین‌های اضافه آمار، کاربران، اعطا و لغو دسترسی را می‌بینند؛ بقیه‌ی بخش‌ها فقط برای مالک است.",
    "👮 <b>Admin management</b>\n\n👑 Owner: {owner}\n\n👮 Extra admins:\n{lines}\n\nExtra admins get stats, users, grant & revoke; everything else is owner-only.")
add("ad_none", "— هنوز کسی نیست —", "— nobody yet —")
add("ad_add", "➕ افزودن ادمین", "➕ Add admin"); add("ad_owner", "🔁 تغییر مالک", "🔁 Change owner")
add("ad_ask_add", "🆔 شناسه‌ی عددی یا @نام‌کاربری ادمین جدید را بفرست:\n(/cancel برای انصراف)", "🆔 Send the new admin's numeric ID or @username:\n(/cancel to abort)")
add("ad_added", "✅ {who} به ادمین‌ها اضافه شد.", "✅ {who} was added as admin.")
add("ad_is_owner", "این کاربر همین الان مالک است 👑", "That user is already the owner 👑")
add("ad_removed", "🗑 {who} از ادمین‌ها حذف شد.", "🗑 {who} was removed from admins.")
add("ad_notify_new", "👮 تو به‌عنوان ادمین ربات انتخاب شدی! /admin را بزن 🎉", "👮 You've been made an admin of the bot! Send /admin 🎉")
add("ad_notify_removed", "ℹ️ دسترسی ادمین تو برداشته شد.", "ℹ️ Your admin access was removed.")
add("ad_owner_ask", "🔁 شناسه‌ی عددی یا @نام‌کاربری مالک جدید را بفرست:\n⚠️ بعد از تأیید، تو دیگر مالک نیستی.\n(/cancel برای انصراف)", "🔁 Send the new owner's numeric ID or @username:\n⚠️ After confirming you will no longer be the owner.\n(/cancel to abort)")
add("ad_owner_confirm", "مالکیت به {who} منتقل شود؟", "Transfer ownership to {who}?")
add("ad_owner_done", "✅ مالک جدید: {who}", "✅ New owner: {who}")
add("ad_owner_notify_new", "👑 تو حالا مالک ربات هستی! /admin را بزن.", "👑 You are now the owner of the bot! Send /admin.")
add("ad_owner_same", "این کاربر همین الان مالک است.", "That user is already the owner.")
add("su_menu", "💬 <b>مخاطبین پشتیبانی</b>\n\n1️⃣ اصلی: @{p}\n2️⃣ دوم: {b}\n\nدر دکمه‌ی «پیام به ادمین» به کاربران نشان داده می‌شود.", "💬 <b>Support contacts</b>\n\n1️⃣ Primary: @{p}\n2️⃣ Backup: {b}\n\nShown to users on the “Contact admin” button.")
add("su_b_primary", "✏️ تغییر اصلی", "✏️ Edit primary"); add("su_b_backup", "✏️ تنظیم پشتیبان دوم", "✏️ Set backup"); add("su_b_clear", "🧹 حذف پشتیبان دوم", "🧹 Remove backup")
add("su_ask", "✏️ نام‌کاربری تلگرام (مثلاً @example) را بفرست:\n(/cancel برای انصراف)", "✏️ Send the Telegram username (e.g. @example):\n(/cancel to abort)")
add("su_bad", "نام‌کاربری نامعتبر است (۵ تا ۳۲ حرف انگلیسی/عدد/_).", "Invalid username (5–32 letters/digits/_).")
add("su_saved", "✅ ذخیره شد.", "✅ Saved."); add("su_cleared", "🧹 پشتیبان دوم حذف شد.", "🧹 Backup removed."); add("su_none", "(تنظیم نشده)", "(not set)")
# price plans
add("pp_mgr", "💰 <b>قیمت‌ها و پلن‌ها</b>\n\n{lines}\n\nهر پلن یک «تعداد دانلود» (اجباری) و یک متن قیمت دارد. تا وقتی هر دو پر نشوند، پلن برای کاربران مخفی است. پرداخت را دستی خودت انجام می‌دهی؛ از بخش «اعطای دسترسی» اعتبار بده.",
    "💰 <b>Prices & plans</b>\n\n{lines}\n\nEach plan needs a download count (required) and a price text; until both are set the plan stays hidden from users. Payment is handled manually — grant credits via “Grant access”.")
add("pp_none", "— هنوز پلنی تعریف نشده —", "— no plans yet —")
add("pp_line", "{pos}. {star}{title} — {count} · {price}{dur}{hid}", "{pos}. {star}{title} — {count} · {price}{dur}{hid}")
add("pp_hidden", " · 🙈 مخفی", " · 🙈 hidden")
add("pp_add", "➕ افزودن پلن", "➕ Add plan"); add("pp_clear", "🧹 پاک کردن همه", "🧹 Clear all")
add("pp_full", "به سقف {n} پلن رسیدی.", "You've reached the limit of {n} plans.")
add("pp_deleted", "🗑 پلن حذف شد.", "🗑 Plan deleted."); add("pp_cleared", "🧹 همه‌ی پلن‌ها پاک شد.", "🧹 All plans cleared.")
add("pp_clear_confirm", "همه‌ی پلن‌ها پاک شوند؟", "Clear all plans?"); add("pp_gone", "این پلن وجود ندارد.", "That plan doesn't exist.")
add("pp_ask_title", "✏️ نام پلن را بفرست (مثلاً «پایه»):\n(/cancel برای انصراف)", "✏️ Send the plan name (e.g. “Basic”):\n(/cancel to abort)")
add("pp_ask_count", "🎟 تعداد دانلود این پلن را بفرست (عدد بزرگ‌تر از صفر):", "🎟 Send the download count for this plan (number above zero):")
add("pp_ask_price", "💵 متن قیمت را بفرست (هر متن و واحد پولی):", "💵 Send the price text (any text/currency):")
add("pp_ask_dur", "⏳ اختیاری: مدت (مثلاً «ماهانه») یا رد کن:", "⏳ Optional: duration (e.g. “per month”) or skip:")
add("pp_ask_feat", "🌟 اختیاری: ویژگی‌ها را با | یا ; جدا کن (مثلاً «بدون تبلیغ | پشتیبانی»):", "🌟 Optional: features separated by | or ; (e.g. “No ads | Support”):")
add("pp_ask_pop", "⭐ با نشان «محبوب‌ترین» نمایش داده شود؟", "⭐ Show with the “Popular” badge?")
add("pp_skip", "⏭ رد کردن", "⏭ Skip"); add("pp_added", "✅ پلن اضافه شد.", "✅ Plan added."); add("pp_saved", "✅ پلن ذخیره شد.", "✅ Plan saved.")
add("pp_edit_menu", "✏️ ویرایش پلن #{id}\n\n{card}\n\n(برای پاک کردن مدت/ویژگی‌ها «-» بفرست)", "✏️ Edit plan #{id}\n\n{card}\n\n(send “-” to clear duration/features)")
add("pp_e_title", "✏️ نام", "✏️ Name"); add("pp_e_count", "🎟 تعداد", "🎟 Count"); add("pp_e_price", "💵 قیمت", "💵 Price")
add("pp_e_dur", "⏳ مدت", "⏳ Duration"); add("pp_e_feat", "🌟 ویژگی‌ها", "🌟 Features"); add("pp_e_pop", "⭐ محبوب: {s}", "⭐ Popular: {s}")
add("pp_quick", "⚡ پلن‌ها (میان‌بر):", "⚡ Plans (quick):")
add("pp_quick_credits", "{title} (+{n} 💎)", "{title} (+{n} 💎)")
# ads admin
add("ads_mgr", "📢 <b>تبلیغات</b>\n\nوضعیت: {s} · نمایش بعد از هر {every} دانلود\n(تبلیغ به کاربران ویژه/اعتباردار نشان داده نمی‌شود)\n\n{lines}",
    "📢 <b>Ads</b>\n\nStatus: {s} · shown after every {every} downloads\n(ads are never shown to premium/credit users)\n\n{lines}")
add("ads_none", "— هنوز تبلیغی نیست —", "— no ads yet —")
add("ads_line", "{st} #{id} · 👁 {views} · 🖱 {clicks}\n   {preview}", "{st} #{id} · 👁 {views} · 🖱 {clicks}\n   {preview}")
add("ads_b_add", "➕ تبلیغ جدید", "➕ New ad"); add("ads_b_every", "🔢 هر N دانلود", "🔢 Every N downloads")
add("ads_b_toggle", "📢 تبلیغات: {s}", "📢 Ads: {s}"); add("ads_b_bc", "📣 ارسال تبلیغ به همه", "📣 Broadcast an ad")
add("ads_ask_fa", "📝 متن فارسی تبلیغ را بفرست (یا عکس همراه کپشن بفرست):\n(/cancel برای انصراف)", "📝 Send the Persian ad text (or a photo with a caption):\n(/cancel to abort)")
add("ads_ask_en", "📝 متن انگلیسی را بفرست (یا رد کن تا همان فارسی استفاده شود):", "📝 Send the English text (or skip to reuse the Persian one):")
add("ads_ask_photo", "🖼 عکس تبلیغ را بفرست (اختیاری):", "🖼 Send the ad photo (optional):")
add("ads_ask_url", "🔗 لینک دکمه‌ی تبلیغ را بفرست (https://…) (اختیاری):", "🔗 Send the ad button URL (https://…) (optional):")
add("ads_ask_btn", "🏷 متن دکمه را بفرست (اختیاری):", "🏷 Send the button label (optional):")
add("ads_bad_url", "لینک باید با http:// یا https:// شروع شود.", "The URL must start with http:// or https://.")
add("ads_added", "✅ تبلیغ اضافه شد.", "✅ Ad added."); add("ads_saved", "✅ ذخیره شد.", "✅ Saved.")
add("ads_gone", "این تبلیغ وجود ندارد.", "That ad doesn't exist.")
add("ads_deleted", "🗑 تبلیغ حذف شد.", "🗑 Ad deleted.")
add("ads_edit", "📢 تبلیغ #{id} — {st}\n👁 نمایش: {views} · 🖱 کلیک: {clicks}\n🖼 عکس: {photo}\n🔗 {url}\n🏷 {btn}\n🖱 شمارش کلیک: {track}\n\n🇮🇷 {fa}\n\n🇬🇧 {en}",
    "📢 Ad #{id} — {st}\n👁 Views: {views} · 🖱 Clicks: {clicks}\n🖼 Photo: {photo}\n🔗 {url}\n🏷 {btn}\n🖱 Click counting: {track}\n\n🇮🇷 {fa}\n\n🇬🇧 {en}")
add("ads_b_fa", "✏️ متن فارسی", "✏️ Persian text"); add("ads_b_en", "✏️ متن انگلیسی", "✏️ English text")
add("ads_b_photo", "🖼 عکس", "🖼 Photo"); add("ads_b_url", "🔗 لینک", "🔗 URL"); add("ads_b_btn", "🏷 دکمه", "🏷 Button label")
add("ads_b_enabled", "فعال: {s}", "Enabled: {s}"); add("ads_b_track", "🖱 شمارش کلیک: {s}", "🖱 Count clicks: {s}")
add("ads_b_preview", "👁 پیش‌نمایش", "👁 Preview"); add("ads_b_del", "🗑 حذف", "🗑 Delete")
add("ads_st_on", "🟢", "🟢"); add("ads_st_off", "⚪️", "⚪️")
add("ads_bc_pick", "📣 کدام تبلیغ برای همه ارسال شود؟ (فقط غیرویژه‌ها)", "📣 Which ad should be broadcast? (non-premium users only)")
add("ads_bc_confirm", "📣 تبلیغ #{id} برای {n} کاربر ارسال شود؟", "📣 Send ad #{id} to {n} users?")
add("ads_none_ready", "اول یک تبلیغ بساز.", "Create an ad first.")
# channels admin
add("ch_mgr", "📌 <b>کانال‌های اجباری</b>\n\nکاربران باید عضو همه‌ی این‌ها باشند (پیشنهاد: حداکثر ۵ کانال). ربات باید در هر کانال ادمین باشد.\n\n{lines}",
    "📌 <b>Required channels</b>\n\nUsers must join all of these (recommended ≤5). The bot must be an admin in each channel.\n\n{lines}")
add("ch_none", "— هنوز کانالی تعریف نشده —", "— no channels yet —")
add("ch_b_add", "➕ افزودن کانال", "➕ Add channel")
add("ch_ask", "📌 @نام‌کاربری یا شناسه‌ی عددی کانال (مثل -100123…) را بفرست.\nاول ربات را در کانال ادمین کن.\n(/cancel برای انصراف)",
    "📌 Send the channel @username or numeric ID (like -100123…).\nMake the bot an admin of the channel first.\n(/cancel to abort)")
add("ch_err_notfound", "❌ کانال پیدا نشد. نام‌کاربری/شناسه را بررسی کن.", "❌ Channel not found. Check the username/ID.")
add("ch_err_notadmin", "❌ ربات در این کانال ادمین نیست (یا به کانال دسترسی ندارد). اول ربات را ادمین کانال کن و دوباره بفرست.", "❌ The bot isn't an admin in this channel (or can't access it). Make it an admin first, then send again.")
add("ch_err_dup", "این کانال قبلاً اضافه شده.", "This channel was already added.")
add("ch_ask_url", "🔗 لینک عضویت کانال (https://t.me/…) را بفرست:", "🔗 Send the channel join link (https://t.me/…):")
add("ch_added", "✅ کانال «{title}» اضافه شد.", "✅ Channel “{title}” added.")
add("ch_removed", "🗑 کانال حذف شد.", "🗑 Channel removed.")
add("ch_many", "⚠️ بیش از ۵ کانال اجباری ممکن است کاربران را خسته کند.", "⚠️ More than 5 required channels may annoy users.")
add("ch_lost", "⚠️ ربات دسترسی کانال «{title}» را از دست داده (ادمین نیست/حذف شده). فعلاً این کانال نادیده گرفته می‌شود (fail-open). لطفاً ربات را دوباره ادمین کن.",
    "⚠️ The bot lost access to channel “{title}” (not admin / removed). It's being skipped for now (fail-open). Please re-add the bot as admin.")
# cookies / engine
add("ck_menu", "🍪 <b>کوکی‌ها</b>\n\nبرای استوری/هایلایت/محتوای خصوصی اینستاگرام و ویدیوهای یوتیوبِ محدودشده، فایل <code>cookies.txt</code> (فرمت Netscape) را از مرورگر خودت صادر کن و اینجا آپلود کن.\n⚠️ از حساب فرعی استفاده کن؛ رمز عبور هرگز لازم نیست.\n\n{lines}",
    "🍪 <b>Cookies</b>\n\nFor Instagram stories/highlights/private content and restricted YouTube videos, export a <code>cookies.txt</code> (Netscape format) from your browser and upload it here.\n⚠️ Use a secondary account; passwords are never needed.\n\n{lines}")
add("ck_line_set", "{p}: ✅ {n} کوکی · {date}", "{p}: ✅ {n} cookies · {date}")
add("ck_line_none", "{p}: ❌ تنظیم نشده", "{p}: ❌ not set")
add("ck_b_up", "📤 آپلود {p}", "📤 Upload {p}"); add("ck_b_del", "🗑 حذف {p}", "🗑 Delete {p}")
add("ck_ask", "📤 فایل cookies.txt مربوط به {p} را به‌صورت «فایل» (Document) بفرست.\nپیامت بعد از ذخیره پاک می‌شود.\n(/cancel برای انصراف)", "📤 Send the cookies.txt for {p} as a document (file).\nYour message will be deleted after saving.\n(/cancel to abort)")
add("ck_bad", "❌ فایل معتبر نیست (فرمت Netscape یا کوکی مربوط به {p} پیدا نشد).", "❌ Invalid file (no Netscape-format cookies for {p} found).")
add("ck_saved", "✅ کوکی {p} ذخیره شد ({n} مورد). پیام آپلود پاک شد 🔒", "✅ {p} cookies saved ({n} entries). Your upload message was deleted 🔒")
add("ck_deleted", "🗑 کوکی {p} حذف شد.", "🗑 {p} cookies deleted.")
add("ck_need_doc", "لطفاً فایل را به‌صورت Document بفرست.", "Please send the file as a document.")
add("up_running", "🔄 در حال به‌روزرسانی yt-dlp و gallery-dl …", "🔄 Updating yt-dlp and gallery-dl …")
add("up_done", "✅ به‌روزرسانی انجام شد.\nyt-dlp: {y}\ngallery-dl: {g}", "✅ Update finished.\nyt-dlp: {y}\ngallery-dl: {g}")
add("up_fail", "❌ به‌روزرسانی ناموفق بود:\n{d}", "❌ Update failed:\n{d}")

add("ask_profile", "📸 یوزرنیم اینستاگرام (مثلاً <code>@username</code>) یا لینک پروفایل رو بفرست:\n(/cancel برای انصراف)", "📸 Send an Instagram username (like <code>@username</code>) or a profile link:\n(/cancel to abort)")
add("bad_username", "🤔 یوزرنیم معتبر نیست. مثل <code>@username</code> بفرست.", "🤔 That doesn't look like a valid username. Send something like <code>@username</code>.")
add("profile_lowres", "ℹ️ اینستاگرام فقط نسخه‌ی کوچیک عکس پروفایل رو بدون ورود نشون می‌ده؛ برای کیفیت کامل، ادمین باید کوکی اینستاگرام رو فعال کنه.", "ℹ️ Without a login Instagram only exposes a small version of the profile picture; for full resolution the admin must enable Instagram cookies.")
add("b_dl_again", "🔁 دوباره", "🔁 Again")
add("busy_probe", "⏳ چند لینک همزمان در حال بررسی‌ه؛ چند لحظه صبر کن.", "⏳ Several links are being processed right now; wait a moment.")
add("too_many_links", "ℹ️ فقط {n} لینک اول رو بررسی می‌کنم.", "ℹ️ I'll only process the first {n} links.")
add("gate_admin_alert", "⚠️ {msg}", "⚠️ {msg}")
add("plat_youtube", "▶️ یوتیوب", "▶️ YouTube"); add("plat_instagram", "📸 اینستاگرام", "📸 Instagram")
add("plat_tiktok", "🎵 تیک‌تاک", "🎵 TikTok"); add("plat_pinterest", "📌 پینترست", "📌 Pinterest"); add("plat_linkedin", "💼 لینکدین", "💼 LinkedIn")

add("ch_b_add", "➕ افزودن کانال", "➕ Add channel")

add("no_audio_warn", "ℹ️ به نظر می‌رسه این ویدیو در خود منبع صدا نداشت (یا اینستاگرام نسخه‌ی بی‌صدا داد).", "ℹ️ This video seems to have no audio at the source (or Instagram only served a silent version).")

# ---------- SoundCloud / Spotify ----------
add("plat_soundcloud", "☁️ ساندکلود", "☁️ SoundCloud"); add("plat_spotify", "🎧 اسپاتیفای", "🎧 Spotify")
add("opt_audio_title", "🎧 <b>{title}</b>\n{meta}\n\nکدوم قالب صوتی؟ 👇", "🎧 <b>{title}</b>\n{meta}\n\nWhich audio format? 👇")
add("opt_coll_title", "💿 <b>{title}</b>\n👤 {who}\n🎼 {n} آهنگ آماده‌ست (از {total})", "💿 <b>{title}</b>\n👤 {who}\n🎼 {n} track(s) ready (of {total})")
add("coll_limited", "\nℹ️ فقط {n} آهنگ اول از {total} گرفته می‌شه. برای بقیه، لینک تک‌تک آهنگ‌ها رو بفرست.", "\nℹ️ Only the first {n} of {total} tracks will be taken. Send single track links for the rest.")
add('spotify_honest', '\n\n🔎 اسپاتیفای فایل صوتی نمی\u200cده؛ این آهنگ از «{src}» پیدا شد:\n<i>{yt}</i>\n(ممکنه دقیقاً همون نسخه\u200cی اسپاتیفای نباشه)', "\n\n🔎 Spotify doesn't serve audio files; this track was matched on “{src}”:\n<i>{yt}</i>\n(it may not be the exact Spotify version)")
add('spotify_honest_coll', '\n\n🔎 اسپاتیفای فایل صوتی نمی\u200cده؛ هر آهنگ از روی مشخصاتش توی منابع موسیقی (رادیو جوان، ساندکلود، آدیوس، بندکمپ، یوتیوب موزیک) پیدا و ارسال می\u200cشه. هر آهنگ یک دانلود حساب می\u200cشه.', "\n\n🔎 Spotify doesn't serve audio files; each track is matched from its details in music sources (Radio Javan, SoundCloud, Audius, Bandcamp, YouTube Music). Each track counts as one download.")
add("b_coll_mp3", "🎵 همه {n} آهنگ (MP3)", "🎵 All {n} tracks (MP3)"); add("b_coll_m4a", "🎵 همه {n} آهنگ (M4A)", "🎵 All {n} tracks (M4A)")
add("coll_progress", "⏳ آهنگ {i} از {n}…", "⏳ Track {i} of {n}…")
add("coll_done", "✅ {done} آهنگ فرستاده شد{skip_note}", "✅ {done} track(s) sent{skip_note}")
add("about",
    "📥 <b>SaveIt</b> — دانلودر لینک به فایل 💖\n\n▶️ یوتیوب · 📸 اینستاگرام · 🎵 تیک‌تاک · 📌 پینترست · 💼 لینکدین · 🧵 تردز · 🐦 توییتر/ایکس · ☁️ ساندکلود · 🎧 اسپاتیفای · 🎶 شناسایی آهنگ\n\n"
    "🎶 شناسایی آهنگ: ویس/آهنگ/کلیپ بفرست تا اسمش رو پیدا کنم (روی آهنگ‌های خارجی بهتر جواب می‌ده؛ آهنگ‌های محلی/ایرانی ممکنه شناسایی نشن).\n\n"
    "ℹ️ درباره‌ی اسپاتیفای: اسپاتیفای فایل صوتی رایگان نمی‌ده. ربات فقط اطلاعات عمومی آهنگ (نام، خواننده، مدت، کاور) رو می‌خونه، بهترین تطابق رو توی منابع موسیقی (رادیو جوان، ساندکلود، آدیوس، بندکمپ و در آخر یوتیوب موزیک) پیدا می‌کنه و صدای اون رو می‌فرسته؛ پس ممکنه با نسخه‌ی اسپاتیفای کمی فرق داشته باشه.\n"
    "📦 حداکثر حجم فایل ۵۰ مگابایت (محدودیت تلگرام).\n\n"
    "📢 برای تبلیغات به پشتیبانی پیام بدید: @{sp}\n\n"
    "⚖️ مسئولیت رعایت حقوق صاحبان محتوا با خود شماست.",
    "📥 <b>SaveIt</b> — link-to-file downloader 💖\n\n▶️ YouTube · 📸 Instagram · 🎵 TikTok · 📌 Pinterest · 💼 LinkedIn · 🧵 Threads · 🐦 Twitter/X · ☁️ SoundCloud · 🎧 Spotify · 🎶 Song recognition\n\n"
    "🎶 Song recognition: send a voice/audio/clip and I'll find the song (works best for international music; local songs may not be recognized).\n\n"
    "ℹ️ About Spotify: Spotify doesn't provide free audio files. The bot only reads the song's public info (title, artist, duration, cover), finds the best match in music sources (Radio Javan, SoundCloud, Audius, Bandcamp, finally YouTube Music) and sends that audio, so it may differ slightly from the Spotify version.\n"
    "📦 Max file size is 50 MB (Telegram's limit).\n\n"
    "📢 For advertising, contact support: @{sp}\n\n"
    "⚖️ You are responsible for respecting content owners' rights.")

# ---------- per-platform free quota ----------
add("lim_unl", "♾ نامحدود", "♾ unlimited"); add("lim_blocked", "⛔ بسته", "⛔ blocked")
add("me_free_head", "🆓 <b>سهمیه‌ی رایگان امروز (باقی‌مانده از کل)</b>", "🆓 <b>Free downloads today (left of total)</b>")
add("quota_out_plat", "سهمیه‌ی رایگان امروزت برای {plat} تموم شد! ({used} از {limit})", "You've used today's free {plat} downloads! ({used} of {limit})")
add("quota_blocked", "دانلود رایگان از {plat} فعلاً بسته است 🔒 (با اعتبار یا پلن ویژه کار می‌کنه)", "Free downloads from {plat} are currently closed 🔒 (credits or a premium plan still work)")
add("quota_out_all", "سهمیه‌ی رایگان امروزت تموم شد!", "You've used up today's free downloads!")
add("quota_left_elsewhere", "✅ هنوز می‌تونی رایگان بگیری از:\n{lines}", "✅ You can still download free from:\n{lines}")
add("a_b_limits", "⚙️ سهمیه‌ی رایگان هر پلتفرم", "⚙️ Free limits per platform")
add("a_limits",
    "⚙️ <b>سهمیه‌ی رایگان روزانه به تفکیک پلتفرم</b>\n\n{lines}\n\n🔢 پیش‌فرض کلی: {default} در روز (برای پلتفرم‌هایی که تنظیم جدا ندارند)\n\n"
    "• عدد ۰ = بسته برای کاربران رایگان\n• ♾ = نامحدود\n• اعتبار/پلن‌های ویژه و ادمین‌ها مثل قبل کار می‌کنند؛ اعتبار روی همه‌ی پلتفرم‌ها (حتی بسته‌ها) خرج می‌شود.",
    "⚙️ <b>Free daily quota per platform</b>\n\n{lines}\n\n🔢 Global default: {default}/day (for platforms without their own setting)\n\n"
    "• 0 = closed for free users\n• ♾ = unlimited\n• Credits, premium plans and admins work as before; credits are spent on any platform (even closed ones).")
add("a_limit_line", "{plat}: {val}{tag}", "{plat}: {val}{tag}")
add("a_limit_default_tag", " (پیش‌فرض)", " (default)")
add("a_limit_plat", "⚙️ <b>{plat}</b>\nسهمیه‌ی رایگان فعلی: {val}{tag}\n\nچی می‌خوای؟", "⚙️ <b>{plat}</b>\nCurrent free limit: {val}{tag}\n\nWhat do you want?")
add("a_limit_set", "✏️ عدد دلخواه", "✏️ Custom number"); add("a_limit_unl", "♾ نامحدود", "♾ Unlimited")
add("a_limit_zero", "⛔ بستن (۰)", "⛔ Close (0)"); add("a_limit_reset", "↩️ پیش‌فرض کلی", "↩️ Use global default")
add("a_limit_ask", "🔢 سهمیه‌ی روزانه‌ی رایگان {plat} را به صورت عدد بفرست (۰ تا ۱۰۰۰۰۰):\n(/cancel برای انصراف)", "🔢 Send the free daily limit for {plat} as a number (0 to 100000):\n(/cancel to abort)")
add("a_s_maxtracks", "🎼 حداکثر آهنگ", "🎼 Max tracks")
add("coll_skip_note", " · {k} مورد نشد (پیدا نشد/خطا)", " · {k} could not be fetched (no match/error)")

# ---------- music recognition ----------
add("plat_threads", "🧵 تردز", "🧵 Threads"); add("plat_twitter", "🐦 توییتر / ایکس", "🐦 Twitter / X")
add("plat_music_id", "🎶 شناسایی آهنگ", "🎶 Music recognition")
add("mid_listening", "🎧 دارم گوش می‌دم… (چند ثانیه صبر کن)", "🎧 Listening… (give me a few seconds)")
add("mid_found", "🎶 <b>{title}</b>\n👤 {artist}\n💿 {meta}\n\nهمین بود؟ 👇", "🎶 <b>{title}</b>\n👤 {artist}\n💿 {meta}\n\nIs this it? 👇")
add("mid_found_nometa", "🎶 <b>{title}</b>\n👤 {artist}\n\nهمین بود؟ 👇", "🎶 <b>{title}</b>\n👤 {artist}\n\nIs this it? 👇")
add("mid_b_dl", "⬇️ دانلود", "⬇️ Download"); add('mid_b_others', '🔎 نتایج دیگه', '🔎 Other results')
add("mid_b_x", "❌", "❌"); add("mid_b_search", "🔎 جستجوی این آهنگ", "🔎 Search this song")
add('mid_others', '🔎 کدوم رو می\u200cخوای؟ 👇', '🔎 Which one do you want? 👇')
add("mid_nomatch",
    "🤷 آهنگ رو نشناختم.\n\n💡 نکته‌ها:\n• ۱۰ تا ۲۰ ثانیه از موزیک واضح بفرست\n• نویز و صحبت پس‌زمینه کم باشه\n• صدای خود آهنگ باشه، نه زمزمه (زمزمه پشتیبانی نمی‌شه)\n• آهنگ‌های محلی/ایرانی ممکنه شناسایی نشن؛ اسمش رو بنویس تا جستجو کنم",
    "🤷 I couldn't recognize that song.\n\n💡 Tips:\n• Send 10–20 seconds of clear music\n• Less noise and background talking\n• The original recording, not humming (humming isn't supported)\n• Local/Iranian songs may not be recognized; type the name and I'll search")
add("mid_toobig", "📦 فایل بزرگ‌تر از ۲۰ مگابایته؛ یه بخش کوتاه‌تر (۱۰ تا ۲۰ ثانیه) بفرست.", "📦 That file is over 20 MB; please send a shorter part (10–20 seconds).")
add("mid_noaudio", "🔇 توی این فایل صدایی پیدا نکردم.", "🔇 I couldn't find any audio in that file.")
add("mid_convert", "😵 نتونستم این فایل رو پردازش کنم. یه ویس یا فایل صوتی دیگه امتحان کن.", "😵 I couldn't process that file. Try another voice message or audio file.")
add("mid_backend", "😵 سرویس شناسایی الان در دسترس نیست؛ کمی بعد دوباره امتحان کن.", "😵 The recognition service is unavailable right now; try again shortly.")
add('mid_matching', '🔎 دارم آهنگ رو توی منابع موسیقی پیدا می\u200cکنم…', '🔎 Looking for the song in music sources…')
add('mid_searching', '🔎 دارم «{q}» رو توی منابع موسیقی جستجو می\u200cکنم…', '🔎 Searching music sources for “{q}”…')
add('mid_search_none', '🤷 چیزی پیدا نشد؛ اسم آهنگ و خواننده رو با هم بنویس (فارسی یا انگلیسی).', '🤷 Nothing found; try the song title together with the artist (Persian or English).')
add('mid_search_res', '🔎 نتایج «{q}»:', '🔎 Results for “{q}”:')
add("mid_search_note", "منبع هر نتیجه آخر خطش هست: RJ رادیو جوان · SC ساندکلود · Audius · BC بندکمپ · YTM یوتیوب موزیک. برای دانلود روی یکی بزن 👇", "The source is at the end of each line: RJ Radio Javan · SC SoundCloud · Audius · BC Bandcamp · YTM YouTube Music. Tap one to download 👇")
add("mid_ask_query", "🔎 اسم آهنگ و/یا خواننده رو بفرست (فارسی یا انگلیسی)، مثلاً: <code>گوگوش پویش</code> یا <code>Rick Astley Never Gonna Give You Up</code>\n(/cancel برای انصراف)", "🔎 Send a song and/or artist name (Persian or English), e.g. <code>Googoosh Pouyesh</code> or <code>Rick Astley Never Gonna Give You Up</code>\n(/cancel to abort)")
add("b_music", "🔎 جستجوی آهنگ", "🔎 Search music")

# =====================================================================================================
# Plans with duration / discounts / downloads per day (these entries intentionally override older ones above)
add("me_until", "📅 دسترسی نامحدود تا: {date} (⏳ {left} روز مانده)", "📅 Unlimited until: {date} (⏳ {left} days left)")
add("plans_card", "✨ <b>{title}</b>\n🎟 {daily}\n💵 ماهانه {price} {unit}\n{rows}{feats}", "✨ <b>{title}</b>\n🎟 {daily}\n💵 {price} {unit} per month\n{rows}{feats}")
add("pp_user_line", "{star}✨ {title} — {daily} — از ماهی {price}", "{star}✨ {title} — {daily} — from {price}/month")
add("pp_line", "{pos}. {star}{title} — {daily} · {price}{hid}", "{pos}. {star}{title} — {daily} · {price}{hid}")
add("pp_quick", "⚡ پلن + مدت (میان‌بر):", "⚡ Plan + duration (quick):")
add("pp_ask_count", "🎟 تعداد دانلود <b>در روز</b> را بفرست (عدد بزرگ‌تر از صفر):", "🎟 Send the number of downloads <b>per day</b> (above zero):")
add("pp_ask_price", "💵 قیمت <b>یک ماه</b> را فقط به‌صورت عدد بفرست (مثلاً 99000). قیمت ۳ و ۶ ماهه با تخفیف خودکار حساب می‌شود. (تا وقتی قیمت نگذاری، پلن برای کاربران مخفی است)", "💵 Send the <b>one-month</b> price as a plain number (e.g. 99000). 3/6-month prices are computed with the discount. (The plan stays hidden from users until a price is set)")
add("pp_edit_menu", "✏️ ویرایش پلن #{id}\n\n{card}\n\n(برای پاک کردن ویژگی‌ها یا قیمت «-» بفرست)", "✏️ Edit plan #{id}\n\n{card}\n\n(send “-” to clear features or price)")
add("pp_mgr", "💰 <b>قیمت‌ها و پلن‌ها</b>\n\n{lines}\n\n🏷 تخفیف مدت: {disc}\n💱 واحد پول: {unit}\n\nهر پلن «دانلود در روز» و «قیمت ماهانه» دارد؛ تا وقتی هر دو پر نشوند مخفی است. قیمت‌ها فقط نمایشی‌اند و پرداخت دستی است؛ از «اعطای دسترسی» پلن + مدت بده.", "💰 <b>Prices & plans</b>\n\n{lines}\n\n🏷 Duration discounts: {disc}\n💱 Currency label: {unit}\n\nEach plan has downloads/day and a monthly price; hidden until both are set. Prices are display-only and payment is manual — use “Grant access” to give plan + duration.")
add("price_unit_default", "تومان", "Toman")
add("daily_n", "{n} دانلود در روز", "{n} downloads/day"); add("daily_unl", "♾ دانلود نامحدود", "♾ unlimited downloads")
add("dur_1m", "۱ ماه", "1 month"); add("dur_3m", "۳ ماه", "3 months"); add("dur_6m", "۶ ماه", "6 months")
add("pp_row", "▫️ {months} ماه: <b>{total}</b> {unit}", "▫️ {months} mo: <b>{total}</b> {unit}")
add("pp_save", "🔥 {pct} تخفیف", "🔥 {pct} off")
add("pp_permonth", "(ماهی {v} {unit})", "({v} {unit}/mo)")
add("pp_best", "🏆 به‌صرفه‌ترین", "🏆 best value")
add("pp_popular_line", "💡 انتخاب اکثر کاربران: دانلود روزانه‌ی زیاد با قیمت مناسب!", "💡 Most users' pick: plenty of daily downloads at a great price!")
add("pp_e_daily", "🎟 دانلود/روز", "🎟 Downloads/day"); add("pp_e_unl", "♾ نامحدود", "♾ Unlimited")
add("pp_ask_daily", "🎟 تعداد دانلود <b>در روز</b> این پلن را بفرست (عدد بزرگ‌تر از صفر) یا «نامحدود» را بزن:\n(/cancel برای انصراف)", "🎟 Send the number of downloads <b>per day</b> (above zero) or press “Unlimited”:\n(/cancel to abort)")
add("pp_quick_plan", "{title} · {daily}", "{title} · {daily}")
add("pp_b_disc", "🏷 تخفیف مدت", "🏷 Duration discounts"); add("pp_b_unit", "💱 واحد پول", "💱 Currency label")
add("pp_disc_menu", "🏷 مدت را انتخاب کن تا درصد تخفیفش را عوض کنی (۱ ماه معمولاً ۰٪):", "🏷 Pick a duration to edit its discount percent (1 month is usually 0%):")
add("pp_disc_reset", "↩️ پیش‌فرض (۰/۱۰/۲۰٪)", "↩️ Defaults (0/10/20%)")
add("pp_ask_disc", "🏷 درصد تخفیف برای {d} را بفرست (۰ تا ۹۰):", "🏷 Send the discount percent for {d} (0–90):")
add("pp_ask_unit", "💱 نام واحد پول را بفرست (مثلاً «تومان»؛ «-» برای پیش‌فرض):", "💱 Send the currency label (e.g. “Toman”; “-” for the default):")
add("a_g_unl_m", "♾ نامحدود {d}", "♾ Unlimited {d}")
add("a_g_custom_days", "✏️ تعداد روز دلخواه", "✏️ Custom days")
add("a_pick_duration", "⏳ مدت پلن «{title}» ({daily}) برای {who} را انتخاب کن (اگر پلن فعال باشد به انقضای فعلی اضافه می‌شود):", "⏳ Pick the duration of plan “{title}” ({daily}) for {who} (added to the current expiry if the plan is already active):")
add("a_done_plan", "✅ پلن «{title}» برای {who} فعال شد: {n} روز، تا {date}.", "✅ Plan “{title}” activated for {who}: {n} days, until {date}.")
add("a_ext_note", "\n➕ به انقضای قبلی اضافه شد.", "\n➕ Added to the previous expiry.")
add("a_status_plan", "💎 پلن {title} تا {date} ({left} روز)", "💎 Plan {title} until {date} ({left} days)")
add("u_plan", "🎁 پلن «{title}» ({daily}) برات فعال شد! {n} روز، تا {date} (⏳ {left} روز مانده) 🥳", "🎁 Your plan “{title}” ({daily}) is active! {n} days, until {date} (⏳ {left} days left) 🥳")
add("u_plan_ext", "➕ پلن «{title}» ({daily}) تمدید شد: {n} روز اضافه شد. انقضا: {date} (⏳ {left} روز مانده) 🥳", "➕ Your plan “{title}” ({daily}) was extended by {n} days. Expires: {date} (⏳ {left} days left) 🥳")
add("u_expiring", "⏰ دسترسی «{name}» تو {n} روز دیگه ({date}) تموم می‌شه. برای تمدید به پشتیبانی پیام بده 💌 (تمدید به انقضای فعلی اضافه می‌شه)", "⏰ Your “{name}” access ends in {n} days ({date}). Message support to extend 💌 (extending adds to the current expiry)")
add("rem_unl_name", "نامحدود", "Unlimited")
add("me_plan", "💎 پلن: <b>{title}</b> — {daily}\n📅 تا {date} (⏳ {left} روز مانده)", "💎 Plan: <b>{title}</b> — {daily}\n📅 Until {date} (⏳ {left} days left)")
add("me_plan_today", "📥 امروز مانده: {n} از {total}", "📥 Left today: {n} of {total}")

# ---- themes
add("b_theme", "🎨 تم", "🎨 Theme")
add("theme_pick", "🎨 <b>تم دکمه‌ها</b>\n\nیکی از چهار فصل رو انتخاب کن؛ همه‌ی دکمه‌های ربات با همون رنگ‌وحال نشون داده می‌شن.\nتم فعلی: {cur}", "🎨 <b>Button theme</b>\n\nPick one of the four seasons; every button in the bot follows it.\nCurrent theme: {cur}")
add("theme_set", "✅ تم روی «{name}» تنظیم شد.", "✅ Theme set to “{name}”.")
add("a_b_theme", "🎨 تم پیش‌فرض", "🎨 Default theme")
add("a_theme", "🎨 <b>تم پیش‌فرض</b> (برای کاربرانی که خودشان انتخاب نکرده‌اند)\n\nانتخاب فعلی: {cur}\nاکنون نمایش داده می‌شود: {now}\n«خودکار» = بر اساس فصل شمسی.", "🎨 <b>Default theme</b> (for users who haven't chosen one)\n\nCurrent choice: {cur}\nShown right now: {now}\n“Auto” follows the Jalali season.")
add("a_th_styles", "🟦 دکمه‌های رنگی تلگرام: {s}", "🟦 Coloured Telegram buttons: {s}")

# ---- lyrics / metadata
add("mid_b_lyrics", "📝 متن آهنگ", "📝 Lyrics")
add("lyr_searching", "📝 دارم متن آهنگ رو پیدا می‌کنم…", "📝 Looking for the lyrics…")
add("lyr_none", "😕 متن این آهنگ رو توی منابع رایگان پیدا نکردم. ببخش!", "😕 Sorry, I couldn't find the lyrics for this song in the free sources.")
add("lyr_head", "📝 <b>{title}</b> — {artist}", "📝 <b>{title}</b> — {artist}")
add("lyr_src", "ℹ️ منبع متن: {src}", "ℹ️ Lyrics source: {src}")

# ---- targeted messaging + channel poster
add('a_b_poster', '📡 پست\u200cگذار کانال', '📡 Channel poster')
add('tm_bc_menu', '📣 <b>پیام به کاربران</b>\nبه همه بفرست یا فقط به کاربران انتخابی:', '📣 <b>Messaging</b>\nSend to everyone or only to selected users:')
add('tm_bc_all', '📣 همه\u200cی کاربران', '📣 All users')
add('tm_bc_sel', '🎯 کاربران انتخابی', '🎯 Selected users')
add('tm_menu', '🎯 <b>پیام به کاربران انتخابی</b>\n\nگیرنده\u200cها تا الان: <b>{n}</b> (دستی انتخاب\u200cشده: {manual})\nزبان: {langf}\nکاربران مسدود همیشه حذف می\u200cشوند.', '🎯 <b>Message selected users</b>\n\nRecipients so far: <b>{n}</b> (picked manually: {manual})\nLanguage: {langf}\nBanned users are always excluded.')
add('tm_all_langs', 'همه', 'all')
add('tm_b_ids', '🆔 لیست آیدی/یوزرنیم', '🆔 ID / @username list')
add('tm_b_pick', '☑️ انتخاب از لیست', '☑️ Pick from list')
add('tm_f_plan', 'دارندگان پلن فعال', 'Active plan holders')
add('tm_f_expired', 'پلن منقضی\u200cشده', 'Expired plans')
add('tm_b_compose', '✉️ نوشتن پیام ({n})', '✉️ Compose ({n})')
add('tm_b_clear', '🧹 پاک\u200cکردن انتخاب', '🧹 Clear')
add('tm_pick', '☑️ کاربران را تیک بزن (انتخاب\u200cشده: {n}):', '☑️ Tick the users (selected: {n}):')
add('tm_done', '✅ تمام ({n})', '✅ Done ({n})')
add('tm_ask_ids', '🆔 آیدی عددی یا @یوزرنیم\u200cها را بفرست (با فاصله، ویرگول یا خط جدید):\n(/cancel برای انصراف)', '🆔 Send numeric IDs or @usernames (separated by spaces, commas or new lines):\n(/cancel to abort)')
add('tm_unknown', '⚠️ این موارد پیدا نشدند و نادیده گرفته شدند: {items}', '⚠️ These were not found and were skipped: {items}')
add('tm_none', '❌ هیچ گیرنده\u200cای انتخاب نشده.', '❌ No recipients selected.')
add('tm_ask_msg', '✉️ پیام را بفرست: متن، عکس (با کپشن) یا هر پیام فورواردشده. همان\u200cطور که هست ارسال می\u200cشود.\n(/cancel برای انصراف)', '✉️ Send the message: text, a photo (with caption) or any forwarded message. It is sent as is.\n(/cancel to abort)')
add('tm_confirm', '👆 پیش\u200cنمایش بالا برای <b>{n}</b> کاربر ارسال می\u200cشود (حدود {rate} پیام در ثانیه). تأیید؟', '👆 The preview above will be sent to <b>{n}</b> users (about {rate} msgs/sec). Confirm?')
add('tm_report', '📊 <b>گزارش ارسال</b>\nکل: {total}\n✅ ارسال\u200cشده: {ok}\n🚫 بلاک/غیرفعال: {blocked}\n❌ ناموفق: {failed}', '📊 <b>Delivery report</b>\nTotal: {total}\n✅ Sent: {ok}\n🚫 Blocked/inactive: {blocked}\n❌ Failed: {failed}')
add('pst_home', '📡 <b>پست\u200cگذار کانال</b>\n\nکانال\u200cها: {nch} · کارهای در حال اجرا: {running}/{total} · فیدها: {feeds}\n\nربات باید در کانال ادمین (با اجازه\u200cی پست) باشد.', '📡 <b>Channel poster</b>\n\nChannels: {nch} · running jobs: {running}/{total} · feeds: {feeds}\n\nThe bot must be an admin (with post rights) in the channel.')
add('pc_add', '➕ افزودن کانال', '➕ Add channel')
add('pc_ask', '📡 @نام\u200cکانال، لینک t.me، آیدی عددی یا یک پست فورواردشده از کانال را بفرست:\n(/cancel برای انصراف)', '📡 Send the @channel, a t.me link, the numeric ID, or forward a post from the channel:\n(/cancel to abort)')
add('pc_err_notfound', '❌ کانال پیدا نشد. اول ربات را ادمین کانال کن و دوباره بفرست.', '❌ Channel not found. Make the bot an admin of the channel first, then send again.')
add('pc_dup', 'این کانال قبلاً اضافه شده.', 'This channel is already added.')
add('pc_full', 'به سقف {n} کانال رسیدی.', "You've reached the limit of {n} channels.")
add('pc_added', '✅ کانال اضافه شد.', '✅ Channel added.')
add('pc_gone', 'این کانال وجود ندارد.', "That channel doesn't exist.")
add('pc_st_ok', '🟢 ربات ادمین است و می\u200cتواند پست کند', '🟢 Bot is an admin and can post')
add('pc_st_notadmin', '🔴 ربات ادمین این کانال نیست', '🔴 The bot is not an admin here')
add('pc_st_nopost', '🟠 ادمین است ولی اجازه\u200cی پست ندارد', '🟠 Admin, but without post rights')
add('pc_st_notfound', '🔴 کانال پیدا نشد', '🔴 Channel not found')
add('pc_card', '📡 <b>{title}</b>\nنشانی: {handle}\nژانر/برچسب: {label}\nهشتگ\u200cهای کانال: {tags}\nزبان فوتر: {fl}\nوضعیت: {status}\nآهنگ\u200cهای پست\u200cشده: {n}\n🆔 <code>{id}</code>', '📡 <b>{title}</b>\nAddress: {handle}\nGenre/label: {label}\nChannel tags: {tags}\nFooter language: {fl}\nStatus: {status}\nTracks posted: {n}\n🆔 <code>{id}</code>')
add('pc_b_label', '🏷 ژانر/برچسب', '🏷 Genre/label')
add('pc_b_handle', '🔗 نشانی کانال', '🔗 Address')
add('pc_b_tags', '#️⃣ هشتگ\u200cها', '#️⃣ Hashtags')
add('pc_b_lang', '🌐 زبان فوتر: {l}', '🌐 Footer language: {l}')
add('pc_b_verify', '🔄 بررسی دوباره', '🔄 Re-verify')
add('pc_ask_label', '🏷 ژانر یا برچسب کانال را بفرست (مثلاً «رپ»، «pop»، «موزیک هوش مصنوعی»؛ «-» برای خالی):', '🏷 Send the channel genre/label (e.g. “rap”, “pop”, “AI music”; “-” to clear):')
add('pc_ask_handle', '🔗 نشانی عمومی کانال را بفرست (@name یا لینک t.me؛ «-» برای حذف):', '🔗 Send the public address (@name or t.me link; “-” to clear):')
add('pc_ask_tags', '#️⃣ هشتگ\u200cهای همیشگی این کانال را بفرست (با فاصله جدا کن، مثلاً: #رپ #ایرانی؛ «-» برای حذف):', "#️⃣ Send this channel's standing hashtags (space separated, e.g. #rap #persian; “-” to clear):")
add('pc_del_confirm', 'این کانال (و کارها/فیدهایش) حذف شود؟', 'Remove this channel (and its jobs/feeds)?')
add('pst_b_jobs', '📋 کارها ({n})', '📋 Jobs ({n})')
add('pst_b_feeds', '📈 فیدهای خودکار ({n})', '📈 Auto feeds ({n})')
add('pst_b_footer', '🦶 فوتر پست', '🦶 Post footer')
add('pst_b_charts', '🛰 منابع چارت', '🛰 Chart sources')
add('pst_b_newjob', '🎵 کار جدید', '🎵 New job')
add('pst_b_newfeed', '📈 فید خودکار', '📈 Auto feed')
add('pst_b_view', '👁 مشاهده', '👁 View')
add('pst_b_review', '👁 بررسی و تأیید', '👁 Review & approve')
add('pst_jobs', '📋 <b>کارهای پست\u200cگذاری</b> ({n})', '📋 <b>Posting jobs</b> ({n})')
add('pst_jobs_none', '— هنوز کاری نیست. از کارت یک کانال «کار جدید» بساز —', '— no jobs yet. Create one from a channel card —')
add('pst_s_draft', '📝 پیش\u200cنویس', '📝 draft')
add('pst_s_running', '▶️ در حال اجرا', '▶️ running')
add('pst_s_paused', '⏸ متوقف', '⏸ paused')
add('pst_s_done', '✅ تمام', '✅ done')
add('pst_s_cancelled', '🚫 لغو', '🚫 cancelled')
add('pst_nolimit', 'بدون سقف', 'no cap')
add('pst_job', '📋 <b>کار #{id} — {name}</b>\nکانال: {ch}\nوضعیت: {st}\nفاصله: هر {iv} دقیقه · سقف روزانه: {daily}\n✅ {ok} · ⏳ {pend} · ❌ {fail} · ⏭ {skip}{err}', '📋 <b>Job #{id} — {name}</b>\nChannel: {ch}\nStatus: {st}\nInterval: every {iv} min · daily cap: {daily}\n✅ {ok} · ⏳ {pend} · ❌ {fail} · ⏭ {skip}{err}')
add('pst_unmatched', '🔎 این موارد پیدا نشدند:\n{items}', '🔎 Not found:\n{items}')
add('pst_b_start', '▶️ شروع پست ({n})', '▶️ Start posting ({n})')
add('pst_b_cancel', '🚫 لغو', '🚫 Cancel')
add('pst_b_pause', '⏸ توقف', '⏸ Pause')
add('pst_b_resume', '▶️ ادامه', '▶️ Resume')
add('pst_b_interval', '⏱ فاصله (دقیقه)', '⏱ Interval (min)')
add('pst_b_daily', '📅 سقف روزانه', '📅 Daily cap')
add('pst_ask_interval', '⏱ فاصله\u200cی بین پست\u200cها را به دقیقه بفرست (حداقل ۱):', '⏱ Send the interval between posts in minutes (min 1):')
add('pst_ask_daily', '📅 حداکثر پست در روز برای هر کانال (۰ = بدون سقف):', '📅 Max posts per day (0 = no cap):')
add('pst_started', '▶️ پست\u200cگذاری شروع شد ({n} آهنگ).', '▶️ Posting started ({n} tracks).')
add('pst_gone', 'این مورد وجود ندارد.', "That item doesn't exist.")
add('pst_searching', '🔎 دارم آهنگ\u200cهای «{q}» را پیدا می\u200cکنم…', '🔎 Looking up “{q}”…')
add('pst_matching', '🔎 دارم {n} آهنگ را در منابع موسیقی پیدا می\u200cکنم…', '🔎 Matching {n} tracks in the music sources…')
add('pst_matching_p', '🔎 {i} از {n} بررسی شد…', '🔎 {i} of {n} checked…')
add('pst_nothing', '😕 چیزی پیدا نشد.\n{items}', '😕 Nothing found.\n{items}')
add('pst_fail', '❌ خطا: {d}', '❌ Error: {d}')
add('pj_type', '🎵 نوع کار را انتخاب کن:', '🎵 Pick the job type:')
add('pj_t_artist', '🎤 همه\u200cی آهنگ\u200cهای یک خواننده', '🎤 All songs of an artist')
add('pj_t_titles', '📝 لیست «خواننده - آهنگ»', '📝 List of “artist - title”')
add('pj_t_query', '🔍 جستجو/پلی\u200cلیست', '🔍 Search / playlist')
add('pj_ask_artist', '🎤 اسم خواننده را بفرست (مثلاً Amir Tataloo):', '🎤 Send the artist name (e.g. Amir Tataloo):')
add('pj_ask_titles', '📝 هر خط یک آهنگ به شکل «خواننده - آهنگ» بفرست (حداکثر ۶۰):', '📝 Send one “artist - title” per line (max 60):')
add('pj_ask_query', '🔍 عبارت جستجو را بفرست (مثلاً «best persian pop»):', '🔍 Send a search query (e.g. “best persian pop”):')
add('pj_name_titles', 'لیست آهنگ\u200cها', 'Title list')
add('pst_done', '🏁 کار «{name}» تمام شد.\n✅ پست\u200cشده: {ok} · ❌ ناموفق: {fail} · ⏭ ردشده: {skip}', '🏁 Job “{name}” finished.\n✅ Posted: {ok} · ❌ Failed: {fail} · ⏭ Skipped: {skip}')
add('pst_paused', '⚠️ کار «{name}» متوقف شد.\n{err}\nبعد از رفع مشکل از «ادامه» استفاده کن.', '⚠️ Job “{name}” was paused.\n{err}\nFix the issue, then press “Resume”.')
add('pst_feeds', '📈 <b>فیدهای خودکار</b> ({n})', '📈 <b>Auto feeds</b> ({n})')
add('pst_feeds_none', '— هنوز فیدی نیست. از کارت یک کانال «فید خودکار» بساز —', '— no feeds yet. Create one from a channel card —')
add('pf_ask_genre', '📈 ژانر فید را بفرست (pop, rap, rock, electronic, dance, rnb, country, jazz, latin…) یا «-» برای همه\u200cی ژانرها:', '📈 Send the feed genre (pop, rap, rock, electronic, dance, rnb, country, jazz, latin…) or “-” for all genres:')
add('pf_name_all', 'همه', 'all')
add('pf_created', '✅ فید ساخته شد. منابع، تعداد و حالت را تنظیم کن.', '✅ Feed created. Adjust the sources, count and mode.')
add('pf_card', '📈 <b>فید #{id} — {name}</b>\nکانال: {ch}\nمنابع: {srcs}\nژانر: {genre}\nتعداد برتر: {top}\nبازخوانی هر {rh} ساعت\nفاصله\u200cی پست: {iv} دقیقه · سقف روزانه: {daily}\nحالت: {mode}\nهشتگ\u200cها: {tags}', '📈 <b>Feed #{id} — {name}</b>\nChannel: {ch}\nSources: {srcs}\nGenre: {genre}\nTop N: {top}\nRefresh every {rh} h\nPost interval: {iv} min · daily cap: {daily}\nMode: {mode}\nHashtags: {tags}')
add('pf_auto', '🤖 خودکار کامل', '🤖 fully automatic')
add('pf_approve', '👁 با تأیید من', '👁 needs my approval')
add('pf_b_genre', '🎼 ژانر', '🎼 Genre')
add('pf_b_top', '🔢 تعداد برتر', '🔢 Top N')
add('pf_b_refresh', '🔁 بازخوانی (ساعت)', '🔁 Refresh (h)')
add('pf_b_tags', '#️⃣ هشتگ\u200cها', '#️⃣ Hashtags')
add('pf_b_auto', '🤖 خودکار: {s}', '🤖 Auto: {s}')
add('pf_b_enabled', '🟢 فعال: {s}', '🟢 Enabled: {s}')
add('pf_b_now', '⚡ همین حالا بساز', '⚡ Build now')
add('pf_ask_top_n', '🔢 تعداد آهنگ\u200cهای برتر (۱ تا ۳۰):', '🔢 How many top tracks (1–30):')
add('pf_ask_refresh_h', '🔁 هر چند ساعت چارت دوباره خوانده شود؟', '🔁 Refresh the chart every how many hours?')
add('pf_ask_interval', '⏱ فاصله\u200cی بین پست\u200cها (دقیقه):', '⏱ Interval between posts (minutes):')
add('pf_ask_daily', '📅 سقف پست روزانه (۰ = بدون سقف):', '📅 Daily post cap (0 = no cap):')
add('pf_ask_tags', '#️⃣ هشتگ\u200cهای اضافه\u200cی این فید را بفرست (با فاصله؛ «-» برای حذف):', '#️⃣ Send extra hashtags for this feed (space separated; “-” to clear):')
add('pf_refreshing', '⏳ دارم چارت را می\u200cخوانم و آهنگ\u200cها را پیدا می\u200cکنم…', '⏳ Reading the chart and matching tracks…')
add('pf_empty', '😕 چیز تازه\u200cای پیدا نشد (همه قبلاً پست شده\u200cاند یا منبع در دسترس نیست).', '😕 Nothing new found (all already posted, or the source is unreachable).')
add('pst_feed_draft', '📈 فید «{name}» آماده است: {n} آهنگ منتظر تأیید توست.', '📈 Feed “{name}” is ready: {n} tracks await your approval.')
add('pst_feed_auto', '📈 فید «{name}» خودکار شروع شد: {n} آهنگ در صف.', '📈 Feed “{name}” started automatically: {n} tracks queued.')
add('pst_charts', '🛰 <b>وضعیت منابع چارت</b>\n{lines}', '🛰 <b>Chart sources status</b>\n{lines}')
add('pst_b_test', '🧪 تست منابع', '🧪 Test sources')
add('pst_testing', '🧪 دارم منابع را تست می\u200cکنم…', '🧪 Testing the sources…')
add('pst_footer', '🦶 <b>فوتر پست</b>\nمتغیرها: {{channel}} نشانی کانال، {{bot}} آدرس ربات، {{botlink}} لینک ربات، {{label}} برچسب\n\nفارسی:\n{fa}\n\nEnglish:\n{en}', '🦶 <b>Post footer</b>\nVariables: {{channel}} channel address, {{bot}} bot address, {{botlink}} bot link, {{label}} label\n\nFarsi:\n{fa}\n\nEnglish:\n{en}')
add('pst_b_default', '↩️ پیش\u200cفرض', '↩️ Defaults')
add('pst_ask_footer', '🦶 متن فوتر را بفرست («-» برای پیش\u200cفرض). از {channel} و {bot} استفاده کن:', '🦶 Send the footer text (“-” for default). Use {channel} and {bot}:')


# ---------- discount codes / referral settings / forced-join label ----------
add("invite_cap_line", "🔒 سقف کل پاداش دعوت: {cap} دانلود", "🔒 Total invite reward cap: {cap} downloads")
add("invite_invitee_line2", "\n🤝 دوستت هم {b} دانلود هدیه می‌گیره!", "\n🤝 Your friend gets {b} free downloads too!")
add("b_code", "🎟 کد تخفیف", "🎟 Discount code")
add("b_code_enter", "🎟 وارد کردن کد تخفیف", "🎟 Enter discount code")
add("code_ask", "🎟 کد تخفیفت رو بفرست (برای انصراف /cancel):", "🎟 Send your discount code (or /cancel):")
add("code_ok_percent", "✅ کد <b>{code}</b> ثبت شد! {pct} تخفیف اضافه روی قیمت پلن‌ها (روی تخفیف مدت هم اعمال می‌شه). قیمت‌ها رو تو صفحه‌ی پلن‌ها ببین 👇",
    "✅ Code <b>{code}</b> saved! {pct} extra off the plan prices (on top of the duration discount). See the prices on the plans screen 👇")
add("code_ok_credits", "✅ کد <b>{code}</b> ثبت شد! وقتی ادمین پلنت رو فعال کنه، {v} دانلود هدیه هم می‌گیری 🎁", "✅ Code <b>{code}</b> saved! You get {v} bonus downloads when the admin activates your plan 🎁")
add("code_ok_days", "✅ کد <b>{code}</b> ثبت شد! وقتی ادمین پلنت رو فعال کنه، {v} روز هدیه هم اضافه می‌شه 🎁", "✅ Code <b>{code}</b> saved! {v} bonus days are added when the admin activates your plan 🎁")
add("code_scope", "محدود به: {scope}", "Limited to: {scope}")
add("code_bad", "❌ این کد وجود نداره. دوباره امتحان کن.", "❌ That code doesn't exist. Try again.")
add("code_disabled", "⚪️ این کد غیرفعاله.", "⚪️ This code is disabled.")
add("code_expired", "⌛️ این کد منقضی شده.", "⌛️ This code has expired.")
add("code_used_up", "🚫 ظرفیت استفاده از این کد تموم شده.", "🚫 This code has no uses left.")
add("code_already", "🚫 قبلاً از این کد استفاده کردی.", "🚫 You have already used this code.")
add("code_throttled", "⏳ تلاش‌های زیاد؛ کمی بعد دوباره امتحان کن.", "⏳ Too many attempts; try again a bit later.")
add("code_pay_note", "پرداخت دستیه؛ بعد از پرداخت، ادمین پلن + کد رو برات ثبت می‌کنه.", "Payment is manual; after paying, the admin activates the plan with your code.")
add("pp_code_row", "🎟 با کد <b>{code}</b> ({pct} اضافه): {months} ماه <b>{total}</b> {unit}", "🎟 With code <b>{code}</b> ({pct} extra): {months} mo <b>{total}</b> {unit}")
add("me_code", "🎟 کد تخفیف فعال: <b>{code}</b> — {what}", "🎟 Active discount code: <b>{code}</b> — {what}")
add("code_what_percent", "{v} تخفیف اضافه", "{v} extra off")
add("code_what_credits", "{v} دانلود هدیه", "{v} bonus downloads")
add("code_what_days", "{v} روز هدیه", "{v} bonus days")
add("u_code_bonus", "🎟 کد <b>{code}</b> اعمال شد: {what} 🎁", "🎟 Code <b>{code}</b> applied: {what} 🎁")
add("a_code_bonus", "🎟 کد <b>{code}</b> این کاربر اعمال و ثبت شد ({what}).", "🎟 This user's code <b>{code}</b> was applied and recorded ({what}).")
add("a_code_holds", "🎟 کد کاربر: <b>{code}</b> — {what} {scope}", "🎟 User's code: <b>{code}</b> — {what} {scope}")
add("a_code_holds_bad", "🎟 کد کاربر: {code} (دیگر معتبر نیست)", "🎟 User's code: {code} (no longer valid)")
# admin codes panel
add("a_b_codes", "🎟 کدهای تخفیف", "🎟 Discount codes")
add("a_b_forced", "📌 کانال‌های اجباری (عضویت)", "📌 Forced-join channels")
add("cd_mgr", "🎟 <b>کدهای تخفیف</b>\n\nپرداخت دستیه؛ کاربر کد رو تو ربات وارد می‌کنه و قیمت‌ها رو با تخفیف می‌بینه، ادمین موقع اعطای پلن کد رو اعمال می‌کنه.\n\n{lines}",
    "🎟 <b>Discount codes</b>\n\nPayment is manual: the user enters the code, sees discounted prices, and the admin applies it when granting a plan.\n\n{lines}")
add("cd_none", "— هنوز کدی نساخته‌ای —", "— no codes yet —")
add("cd_line", "{st} <code>{code}</code> · {what} · استفاده {used}{mx}", "{st} <code>{code}</code> · {what} · used {used}{mx}")
add("cd_b_add", "➕ کد جدید", "➕ New code")
add("cd_ask_code", "🎟 متن کد رو بفرست (۳ تا ۲۰ حرف انگلیسی/عدد، مثل <code>SUMMER25</code>):", "🎟 Send the code text (3-20 letters/digits, e.g. <code>SUMMER25</code>):")
add("cd_bad_code", "❌ فقط حروف انگلیسی، عدد، - و _ (۳ تا ۲۰ کاراکتر).", "❌ Only letters, digits, - and _ (3-20 chars).")
add("cd_dup", "⚠️ این کد قبلاً هست.", "⚠️ That code already exists.")
add("cd_pick_kind", "کد «{code}» چه چیزی بده؟", "What should code “{code}” give?")
add("cd_k_percent", "٪ تخفیف روی قیمت", "% off the price")
add("cd_k_credits", "🎁 دانلود هدیه", "🎁 bonus downloads")
add("cd_k_days", "📅 روز هدیه", "📅 bonus days")
add("cd_ask_val_percent", "🔢 درصد تخفیف (۱ تا ۹۰):", "🔢 Percent off (1-90):")
add("cd_ask_val_credits", "🔢 تعداد دانلود هدیه:", "🔢 Number of bonus downloads:")
add("cd_ask_val_days", "🔢 تعداد روز هدیه:", "🔢 Number of bonus days:")
add("cd_bad_val", "❌ عدد معتبر بفرست.", "❌ Send a valid number.")
add("cd_created", "✅ کد ساخته شد. تنظیماتش رو کامل کن:", "✅ Code created. Fine-tune it:")
add("cd_view", "🎟 <b>{code}</b>\n\n🎁 {what}\nوضعیت: {st}\n⏳ انقضا: {exp}\n🔢 سقف استفاده: {mx}\n👤 هر کاربر فقط یک‌بار: {once}\n📦 پلن: {plan}\n📅 مدت: {months}\n\n📊 استفاده: {used} بار · {uniq} کاربر · {holders} نفر الان این کد رو دارن{hl}",
    "🎟 <b>{code}</b>\n\n🎁 {what}\nStatus: {st}\n⏳ Expires: {exp}\n🔢 Max uses: {mx}\n👤 Once per user: {once}\n📦 Plan: {plan}\n📅 Duration: {months}\n\n📊 Used: {used}× · {uniq} users · {holders} currently hold it{hl}")
add("cd_holders", "\n\n👥 دارندگان: {who}", "\n\n👥 Holders: {who}")
add("cd_b_toggle", "{s} فعال", "{s} Enabled"); add("cd_b_once", "👤 یک‌بار برای هر کاربر: {s}", "👤 Once per user: {s}")
add("cd_b_exp", "⏳ انقضا", "⏳ Expiry"); add("cd_b_max", "🔢 سقف استفاده", "🔢 Max uses")
add("cd_b_plan", "📦 پلن: {p}", "📦 Plan: {p}"); add("cd_b_months", "📅 مدت: {m}", "📅 Duration: {m}")
add("cd_b_val", "✏️ مقدار", "✏️ Value"); add("cd_b_del", "🗑 حذف", "🗑 Delete")
add("cd_any", "همه", "any"); add("cd_never", "بدون انقضا", "never"); add("cd_unl", "نامحدود", "unlimited")
add("cd_ask_exp", "⏳ چند روز دیگه منقضی بشه؟ (۰ = بدون انقضا)", "⏳ Expire in how many days? (0 = never)")
add("cd_ask_max", "🔢 حداکثر دفعات استفاده (۰ = نامحدود):", "🔢 Max number of uses (0 = unlimited):")
add("cd_ask_val", "🔢 مقدار جدید:", "🔢 New value:")
add("cd_confirm_del", "🗑 کد «{code}» حذف بشه؟ (کسانی که الان دارنش هم از دست می‌دن)", "🗑 Delete code “{code}”? (current holders lose it too)")
add("cd_deleted", "🗑 حذف شد.", "🗑 Deleted.")
add("cd_st_on", "🟢 فعال", "🟢 active"); add("cd_st_off", "⚪️ غیرفعال", "⚪️ disabled"); add("cd_st_exp", "⌛️ منقضی", "⌛️ expired"); add("cd_st_used", "🚫 تموم‌شده", "🚫 used up")
add("yes_s", "✅", "✅"); add("no_s", "⬜️", "⬜️")
# referral admin
add("a_s_rmax", "🔒 سقف کل پاداش", "🔒 Total reward cap")
add("a_ref", "🎁 <b>دعوت‌ها</b>\n\nوضعیت: {s}\nکل دعوت‌ها: {total}\nپاداش دعوت‌کننده (به ازای هر دوست): {rb} دانلود\nپاداش دعوت‌شده: {ib} دانلود\nسقف کل پاداش هر کاربر: {cap}\n\n🏆 برترین‌ها:\n{top}",
    "🎁 <b>Referrals</b>\n\nStatus: {s}\nInviter reward (per friend): {rb} downloads\nInvitee bonus: {ib} downloads\nTotal reward cap per user: {cap}\n\nTotal invites: {total}\n🏆 Top inviters:\n{top}")
add("a_ref_hint", "\n\nمقدارها همین الان تو متن «دعوت دوستان» اعمال می‌شن. برای سقف، ۰ = نامحدود.", "\n\nValues apply immediately to the “Invite friends” text. For the cap, 0 = unlimited.")

# ---------- Bale ----------
add("claim_done", "✅ مالک ربات قبلاً مشخص شده.", "✅ The bot already has an owner.")
add("claim_bad", "❌ کد اشتباه است.", "❌ Wrong code.")
add("claim_throttled", "⏳ تلاش‌های زیاد؛ بعداً دوباره امتحان کن.", "⏳ Too many attempts; try again later.")

# ---------- free-access codes / instant redemption ----------
add("cd_k_free", "🎁 دسترسی رایگان (N روز، فوری)", "🎁 Free access (N days, instant)")
add("cd_ask_val_free", "🔢 چند روز دسترسی رایگان؟ (مثلاً ۷):", "🔢 How many days of free access? (e.g. 7):")
add("code_what_free", "{v} روز دسترسی رایگان ({what})", "{v} days free access ({what})")
add("cd_unl_access", "نامحدود", "unlimited")
add("cd_b_access", "📦 دسترسی: {p}", "📦 Access: {p}")
add("code_ok_free_unl", "🎉 کد <b>{code}</b> فعال شد! {n} روز دسترسی <b>نامحدود</b> رایگان داری — تا {date} 🎁", "🎉 Code <b>{code}</b> activated! You have <b>unlimited</b> free access for {n} days — until {date} 🎁")
add("code_ok_free_plan", "🎉 کد <b>{code}</b> فعال شد! پلن «{title}» ({daily}) به مدت {n} روز رایگان فعاله — تا {date} 🎁", "🎉 Code <b>{code}</b> activated! Plan “{title}” ({daily}) is free for {n} days — until {date} 🎁")
add("code_has_longer", "ℹ️ الان دسترسی بلندتری داری (تا {date}) پس این کد لازم نشد و <b>مصرف نشد</b>؛ بعد از پایان دسترسی فعلی می‌تونی دوباره واردش کنی.", "ℹ️ You already have longer access (until {date}), so this code wasn't needed and was <b>not used up</b>; enter it again after your current access ends.")
add("code_has_unlimited", "✅ تو الان دسترسی نامحدود دائمی داری؛ این کد لازم نیست (مصرف نشد).", "✅ You already have permanent unlimited access; this code isn't needed (not used up).")
add("code_plan_gone", "⚠️ پلنِ این کد دیگه موجود نیست؛ به پشتیبانی خبر بده.", "⚠️ The plan behind this code no longer exists; please tell support.")
add("code_ok_credits_now", "🎁 کد <b>{code}</b> ثبت شد! {v} دانلود هدیه همین الان به حسابت اضافه شد 💎", "🎁 Code <b>{code}</b> accepted! {v} bonus downloads were added to your account right now 💎")
add("code_ok_days_now", "🎁 کد <b>{code}</b> ثبت شد! {v} روز به دسترسی فعلیت اضافه شد — تا {date} 📅", "🎁 Code <b>{code}</b> accepted! {v} days were added to your current access — until {date} 📅")
add("code_ok_days", "✅ کد <b>{code}</b> ذخیره شد! الان دسترسی فعالی نداری که تمدید بشه؛ وقتی ادمین پلنت رو فعال کنه، {v} روز هدیه هم اضافه می‌شه 🎁", "✅ Code <b>{code}</b> saved! You have no active access to extend yet; {v} bonus days are added when the admin activates your plan 🎁")

# ---------- diss / beef tags ----------
add("pst_b_diss", "🔥 هشتگ دیس / بیف", "🔥 Diss / beef hashtags")
add("pst_b_edit", "✏️ ویرایش", "✏️ Edit")
add("pst_diss", "🔥 <b>هشتگ‌های دیس و دیس‌بک</b>\nروی آهنگ‌هایی که عنوانشان دیس/diss/بیف دارد یا در لیست دستی‌اند زده می‌شود:\n{tags}", "🔥 <b>Diss / diss-back hashtags</b>\nAdded to tracks whose title has دیس/diss/beef or that are in the hand-made list:\n{tags}")
add("pst_ask_diss", "✏️ هشتگ‌ها را بفرست (با فاصله یا ویرگول جدا کن، مثل #دیس #بیف #Diss):", "✏️ Send the hashtags (separated by spaces or commas, e.g. #دیس #بیف #Diss):")

add("cd_b_rename", "🔤 تغییر متن کد", "🔤 Rename code")
add("cd_renamed", "✅ متن کد عوض شد؛ استفاده‌های قبلی و دارندگان کد حفظ شدند.", "✅ Code text changed; past usage and current holders are kept.")

# ---------- campaign ----------
add("a_b_campaign", "📣 کمپین تبلیغ", "📣 Campaign")
add("cp_home", "📣 <b>کمپین تبلیغ / Campaign</b>\nمتن تبلیغ (فارسی + انگلیسی)، عکس، کد تخفیف پیوست‌شده و ارسال یک‌ضربه به کاربران.\n\n{lines}", "📣 <b>Campaign</b>\nPromo text (fa + en), image, attached discount code and one-tap delivery.\n\n{lines}")
add("cp_line", "{st} {name} — ارسال‌شده: {sent}", "{st} {name} — sent: {sent}")
add("cp_none", "هنوز کمپینی نیست.", "No campaigns yet.")
add("cp_st_draft", "📝", "📝"); add("cp_st_sent", "📤", "📤")
add("cp_b_new", "➕ کمپین جدید", "➕ New campaign")
add("cp_ask_name", "🔤 نام کمپین (فقط برای خودت):", "🔤 Campaign name (only for you):")
add("cp_view", "📣 <b>{name}</b> {st}\n\n🎟 کد پیوست‌شده: {code}\n🖼 عکس: {img} · دکمه‌ی فعال‌سازی: {rb}\n📊 ارسال‌شده: {sent} · بلاک: {blocked} · ناموفق: {failed} · <b>فعال‌سازی کد: {red}</b>\n\n🇮🇷 <b>متن فارسی</b>\n{fa}\n\n🇬🇧 <b>English</b>\n{en}\n\nجاینگهدارها: {{code}} {{benefit}} {{value}} {{expires}} {{max_uses}} {{remaining}} {{conditions}} — از خودِ کد پر می‌شوند.", "📣 <b>{name}</b> {st}\n\n🎟 Attached code: {code}\n🖼 Image: {img} · Redeem button: {rb}\n📊 Sent: {sent} · blocked: {blocked} · failed: {failed} · <b>code redeemed: {red}</b>\n\n🇮🇷 <b>Persian text</b>\n{fa}\n\n🇬🇧 <b>English</b>\n{en}\n\nPlaceholders: {{code}} {{benefit}} {{value}} {{expires}} {{max_uses}} {{remaining}} {{conditions}} - filled live from the code.")
add("cp_nocode", "— (بدون کد)", "— (none)")
add("cp_b_fa", "✏️ متن فارسی", "✏️ Persian text"); add("cp_b_en", "✏️ متن انگلیسی", "✏️ English text")
add("cp_b_img", "🖼 عکس", "🖼 Image"); add("cp_b_imgx", "❌ حذف عکس", "❌ Remove image")
add("cp_b_code", "🎟 انتخاب کد", "🎟 Pick code"); add("cp_b_rb", "🎟 دکمه‌ی فعال‌سازی {s}", "🎟 Redeem button {s}")
add("cp_b_send", "🚀 ارسال…", "🚀 Send…"); add("cp_b_name", "🔤 نام", "🔤 Name")
add("cp_b_default", "↩️ متن پیش‌فرض", "↩️ Default text"); add("cp_b_dup", "📄 کپی", "📄 Duplicate")
add("cp_confirm_del", "🗑 کمپین «{name}» حذف شود؟", "🗑 Delete campaign “{name}”?")
add("cp_ask_text", "✏️ متن جدید را بفرست. فرمت‌های مجاز: &lt;b&gt; &lt;i&gt; &lt;u&gt; &lt;s&gt; &lt;code&gt;. جاینگهدارها: {code} {benefit} {value} {expires} {max_uses} {remaining} {conditions}", "✏️ Send the new text. Allowed formatting: &lt;b&gt; &lt;i&gt; &lt;u&gt; &lt;s&gt; &lt;code&gt;. Placeholders: {code} {benefit} {value} {expires} {max_uses} {remaining} {conditions}")
add("cp_ask_img", "🖼 یک عکس بفرست.", "🖼 Send a photo.")
add("cp_pick_code", "🎟 کدی که به این کمپین وصل شود را انتخاب کن (شرایط کد خودکار در متن می‌آید؛ اگر بعداً کد را ویرایش کنی متن هم به‌روز می‌شود):", "🎟 Pick the code for this campaign (its conditions are filled into the text automatically; editing the code later updates the text):")
add("cp_no_code", "🚫 بدون کد", "🚫 No code")
add("cp_redeem", "🎟 فعال‌سازی کد", "🎟 Redeem code"); add("cp_start", "🚀 شروع", "🚀 Start")
add("cp_cond_once", "هر نفر فقط یک‌بار", "One use per person")
add("cp_cond_max", "ظرفیت: {n} نفر", "Limited to {n} people")
add("cp_cond_exp", "اعتبار تا {date}", "Valid until {date}")
add("cp_f_all", "همه‌ی کاربران", "All users")
add("cp_aud", "🎯 <b>مخاطبان کمپین «{name}»</b>\nهنوز دریافت نکرده: <b>{new}</b> · قبلاً دریافت کرده: {done} · دستی انتخاب‌شده: {manual}\nکاربران مسدود/بلاک‌کرده همیشه حذف می‌شوند.", "🎯 <b>Audience for “{name}”</b>\nNot received yet: <b>{new}</b> · already received: {done} · manually picked: {manual}\nBanned users and users who blocked the bot are always skipped.")
add("cp_b_go", "👀 پیش‌نمایش و ارسال ({n})", "👀 Preview & send ({n})")
add("cp_confirm", "👆 پیش‌نمایش بالا برای <b>{n}</b> کاربر جدید ارسال می‌شود ({done} نفر قبلاً گرفته‌اند). حدود {rate} پیام در ثانیه. تأیید؟", "👆 The preview above goes to <b>{n}</b> new users ({done} already got it). About {rate} msgs/s. Confirm?")
add("cp_b_yes", "✅ ارسال به {n} نفر", "✅ Send to {n}"); add("cp_b_yes_all", "🔁 ارسال دوباره به همه ({n})", "🔁 Resend to everyone ({n})")
add("cp_bad_html", "⚠️ متن پیش‌نمایش ارسال نشد: {err}", "⚠️ Preview failed to send: {err}")
add("cp_report", "📊 <b>گزارش کمپین «{name}»</b>\nکل: {total}\n✅ ارسال‌شده: {ok}\n🚫 بلاک/غیرفعال: {blocked}\n❌ ناموفق: {failed}", "📊 <b>Campaign “{name}” report</b>\nTotal: {total}\n✅ Sent: {ok}\n🚫 Blocked/inactive: {blocked}\n❌ Failed: {failed}")

add("dl_unknown", "😕 این آهنگ دیگه توی لیستم نیست. اسمش رو جستجو کن:", "😕 I no longer have that track on file. Try searching for it:")

# ---------- Telegram Stars support ----------
add("sp_pick", "⭐ <b>حمایت از کانال و ربات</b>\nاگه از ریتم‌باکس و SaveIt خوشت اومده، با چند استارز تلگرام ازمون حمایت کن 💜 (کاملاً اختیاریه و چیزی قفل نمی‌شه)", "⭐ <b>Support the channel & bot</b>\nIf you enjoy RhythmBox and SaveIt, support us with a few Telegram Stars 💜 (completely optional, nothing is locked)")
add("sp_title", "حمایت از ریتم‌باکس و SaveIt", "Support RhythmBox & SaveIt")
add("sp_desc", "حمایت داوطلبانه — ممنون که کنارمونی 💜", "A voluntary tip — thank you for being with us 💜")
add("sp_label", "حمایت", "Support")
add("sp_thanks", "💜 ممنون! {n} ⭐ حمایتت رسید. واقعاً دمت گرم 🙏", "💜 Thank you! Your {n} ⭐ support arrived. Truly appreciated 🙏")
add("sp_fail", "😕 الان نتونستم فاکتور بسازم؛ کمی بعد دوباره امتحان کن.", "😕 I couldn't create the invoice right now; please try again shortly.")
add("sp_b_amounts", "⭐ مبلغ‌های حمایت", "⭐ Support amounts")
add("sp_ask_amounts", "⭐ مبلغ‌ها را به استارز بفرست (تا ۶ عدد، با فاصله؛ مثل ۱۰ ۲۵ ۵۰ ۱۰۰):", "⭐ Send the amounts in Stars (up to 6 numbers, space separated; e.g. 10 25 50 100):")
add("a_stats_sup", "⭐ <b>حمایت با استارز</b>\nتعداد: {n} · مجموع: {stars} ⭐\nمبلغ‌های پیشنهادی: {amounts}", "⭐ <b>Stars support</b>\nCount: {n} · total: {stars} ⭐\nSuggested amounts: {amounts}")

# ---------- viral focus ----------
add("pv_b_home", "🔥 تمرکز وایرال: {s}", "🔥 Viral focus: {s}")
add("pv_b_toggle", "🔥 تمرکز وایرال: {s}", "🔥 Viral focus: {s}")
add("pv_b_add", "➕ افزودن به لیست وایرال", "➕ Add to viral list")
add("pv_b_clear", "🧹 خالی‌کردن لیست", "🧹 Clear list")
add("pv_b_rerank", "🔁 مرتب‌سازی صف فعلی بر اساس امتیاز", "🔁 Re-rank the current queue")
add("pv_tags_short", "هشتگ‌ها", "tags")
add("pv_list_empty", "— (خالی)", "— (empty)")
add("pv_home", "🔥 <b>تمرکز وایرال</b>: {s}\nامتیاز وایرال از روی جایگاه در چارت‌ها (رادیو جوان ترندینگ/محبوب، Audius، iTunes)، تعداد پخش، تازگی، حضور در چند چارت و لیست دستیِ تو محاسبه می‌شود؛ آهنگ‌های معمولی نصف امتیاز می‌گیرند. تخمینی است، نه آمار واقعی ریلز/تیک‌تاک.\n\nهشتگ‌های وایرال: {tags}\nآستانه‌ی وایرال: {vmin} · حداقل صف: {mq}\n\n📋 <b>لیست دستی ({n})</b>\n{lst}", "🔥 <b>Viral focus</b>: {s}\nThe viral score comes from chart position (Radio Javan trending/popular, Audius, iTunes), play counts, recency, presence on several charts and your manual list; ordinary catalogue tracks get half weight. It is an estimate, not real Reels/TikTok data.\n\nViral hashtags: {tags}\nViral threshold: {vmin} · minimum queue: {mq}\n\n📋 <b>Manual list ({n})</b>\n{lst}")
add("pv_ask_tags", "✏️ هشتگ‌های وایرال را بفرست (مثل #وایرال #Viral #Trending):", "✏️ Send the viral hashtags (e.g. #Viral #Trending #ReelsViral):")
add("pv_ask_add", "➕ هر خط یک آهنگ: «خواننده - اسم آهنگ» (می‌توانی چند خط بفرستی). این آهنگ‌ها امتیاز بالا می‌گیرند:", "➕ One track per line: “Artist - Title” (several lines allowed). These get a high score:")
add("pv_added", "✅ {n} آهنگ به لیست وایرال اضافه شد.", "✅ {n} track(s) added to the viral list.")
add("pv_reranking", "⏳ در حال مرتب‌سازی بر اساس امتیاز وایرال…", "⏳ Re-ranking by viral score…")
add("pv_rerank_res", "نگه‌داشته: {kept} · حذف‌شده (غیروایرال): {dropped}", "kept: {kept} · dropped (not viral): {dropped}")
add("pv_none", "—", "—")
